"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Search,School,SlidersHorizontal,AlertTriangle,Database} from "lucide-react";
import {supabase} from "@/lib/supabase";
type Unit={id:string;name:string;unit_type:string;neighborhood:string;address:string;rank:number;hsi:number;ipe:number;ipe_territorial:number|null;priority:string;territorial_priority:string|null;confidence_score:number};
const code=(u:Unit)=>{const p=u.territorial_priority||u.priority||"P4";return p.startsWith("P1")?"P1":p.startsWith("P2")?"P2":p.startsWith("P3")?"P3":"P4"};
const pc=(p:string)=>p==="P1"?"p1":p==="P2"?"p2":p==="P3"?"p3":"p4";
export default function Escolas(){
 const [units,setUnits]=useState<Unit[]>([]);const [q,setQ]=useState("");const [priority,setPriority]=useState("TODAS");const [loading,setLoading]=useState(true);
 useEffect(()=>{supabase().from("units").select("*").order("rank",{ascending:true}).then(({data})=>{setUnits((data as Unit[])||[]);setLoading(false)})},[]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search).get("priority");if(p)setPriority(p)},[]);
 const filtered=useMemo(()=>units.filter(u=>(priority==="TODAS"||code(u)===priority)&&`${u.name} ${u.neighborhood} ${u.address}`.toLowerCase().includes(q.toLowerCase())),[units,q,priority]);
 const counts={P1:units.filter(u=>code(u)==="P1").length,P2:units.filter(u=>code(u)==="P2").length,P3:units.filter(u=>code(u)==="P3").length,P4:units.filter(u=>code(u)==="P4").length};
 const incomplete=units.length>0&&units.length<162;
 return <main className="min-h-screen p-4 md:p-8 max-w-[1500px] mx-auto"><div className="mb-5"><Link href="/" className="muted text-sm hover:text-cyan-300"><ArrowLeft size={15} className="inline mr-1"/> Dashboard</Link><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-3 mt-3"><div><div className="text-cyan-300 text-xs font-bold tracking-widest">BASE TERRITORIAL • HSI-DOTH-P 3.2</div><h1 className="text-3xl md:text-4xl font-black">Escolas e unidades</h1><p className="muted mt-1">Base de trabalho do SIGES · a prioridade territorial é usada quando disponível.</p></div><div className="pill p3">{filtered.length} de {units.length} carregadas</div></div></div>
 {incomplete&&<section className="card p-4 mb-5 border border-amber-700/50"><div className="flex gap-3 items-start"><AlertTriangle size={18} className="text-amber-300 mt-0.5"/><div><strong>Carga ainda não integral</strong><p className="muted text-sm mt-1">O banco está com <b>{units.length}</b> unidades. A matriz de referência possui <b>162</b>. Nenhum registro ausente é inventado pelo sistema.</p></div></div></section>}
 <section className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">{(['P1','P2','P3','P4'] as const).map(p=><Link href={`/escolas?priority=${p}`} key={p} className="card p-4 hover:bg-[#102337] transition flex items-center justify-between"><div><span className={`pill ${pc(p)}`}>{p}</span><div className="muted text-xs mt-2">{p==='P1'?'Crítica':p==='P2'?'Muito alta':p==='P3'?'Alta':'Monitoramento'}</div></div><strong className="text-2xl">{counts[p]}</strong></Link>)}</section>
 <section className="card p-4 mb-5"><div className="grid md:grid-cols-[1fr_auto] gap-3"><div className="flex items-center gap-2 bg-[#07111f] rounded-xl px-3"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar escola, bairro ou endereço..." className="bg-transparent outline-none w-full py-3"/></div><div className="flex items-center gap-2"><SlidersHorizontal size={16}/><select value={priority} onChange={e=>{setPriority(e.target.value);history.replaceState(null,"",e.target.value==="TODAS"?"/escolas":`/escolas?priority=${e.target.value}`)}} className="bg-[#07111f] rounded-xl px-3 py-3 w-full"><option>TODAS</option><option>P1</option><option>P2</option><option>P3</option><option>P4</option></select></div></div></section>
 <section className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{loading?[1,2,3,4,5,6].map(i=><div className="card p-5 h-48 animate-pulse" key={i}/>):filtered.map(u=><Link href={`/escolas/${u.id}`} key={u.id} className="card p-5 hover:bg-[#102337] hover:-translate-y-0.5 transition block"><div className="flex justify-between items-start gap-3"><div className="flex items-center gap-2"><School size={19} className="text-cyan-300"/><span className="muted text-xs">#{u.rank} · {u.unit_type}</span></div><span className={`pill ${pc(code(u))}`}>{code(u)}</span></div><h2 className="font-bold text-lg mt-4 leading-snug">{u.name}</h2><p className="muted text-sm mt-1">{u.neighborhood}</p><p className="muted text-xs mt-1 line-clamp-2">{u.address}</p><div className="grid grid-cols-2 gap-2 mt-5"><div className="bg-[#091624] rounded-xl p-2"><div className="muted text-[11px]">HSI</div><strong>{u.hsi}</strong></div><div className="bg-[#091624] rounded-xl p-2"><div className="muted text-[11px]">IPE Territorial</div><strong>{u.ipe_territorial??u.ipe}</strong></div></div><div className="mt-4 text-cyan-300 text-sm font-semibold flex justify-between">Abrir dossiê <ArrowRight size={16}/></div></Link>)}</section>
 {!loading&&!filtered.length&&<section className="card p-8 mt-4 text-center"><Database className="mx-auto text-cyan-300"/><p className="muted mt-3">Nenhuma unidade corresponde ao filtro atual.</p></section>}
 </main>
}