const express=require('express');

const CBVJ_2025_URL='https://www.cbvj.org.br/blog/bombeiros-voluntarios-de-joinville-atenderam-14-574-ocorrencias-em-2025/';
const CBVJ_2024_URL='https://www.cbvj.org.br/blog/bombeiros-voluntarios-de-joinville-atenderam-mais-de-11-mil-ocorrencias-em-2024/';
const DETRANS_URL='https://www.joinville.sc.gov.br/publicacoes/estudos-tecnicos-equipamentos-de-fiscalizacao-eletronica-radares-e-lombadas/';
const SIMGEO_URL='https://www.joinville.sc.gov.br/servicos/acessar-sistema-de-informacoes-municipais-georreferenciadas-simgeo/';
const SIMGEO_ROOT='https://geo.joinville.sc.gov.br/server/rest/services/simgeo';
const SIMGEO_SCHOOLS='https://geo.joinville.sc.gov.br/server/rest/services/SEPUR/educacao_simgeo_v4/MapServer/1';
const SIMGEO_ROADS='https://geo.joinville.sc.gov.br/server/rest/services/SEPUR/sistema_viario_e_transportes_simgeo_v4/MapServer/1';
const SIMGEO_CYCLE='https://geo.joinville.sc.gov.br/server/rest/services/SEPUR/sistema_viario_e_transportes_simgeo_v4/MapServer/4';
let cache={};
function clean(v){return String(v||'').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim()}
function decode(v){return clean(String(v||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&ndash;/g,'–').replace(/&nbsp;/g,' '))}
function number(v){const n=Number(String(v||'').replace(/\./g,'').replace(',','.'));return Number.isFinite(n)?n:null}
function parseRanking(text){const out=[];const block=text.match(/Ranking[^\n]{0,120}As dez vias com mais acidentes([\s\S]{0,3000}?)(?:Operacional|Fonte:)/i);if(!block)return out;for(const row of block[1].split(/\n+/).map(clean).filter(Boolean)){const m=row.match(/^(?:\d+º?\s*\|\s*)?(?:Rua|Avenida|Av\.?|Rodovia|BR-)?\s*([^|]+?)\s*\|\s*(\d+)\s*\|\s*(?:Rua|Avenida|Av\.?|Rodovia|BR-)?\s*([^|]+?)\s*\|\s*(\d+)$/i);if(m)out.push({road:clean(m[1]),value2024:number(m[2]),road2025:clean(m[3]),value2025:number(m[4])})}return out}
function normalizeRanking(rows){const map=new Map();for(const r of rows){const road=clean(r.road2025||r.road);if(road)map.set(road.toLowerCase(),{road,value2024:r.value2024,value2025:r.value2025})}return[...map.values()].sort((a,b)=>(b.value2025||0)-(a.value2025||0)).map((x,i)=>({...x,rank2025:i+1,variation2024to2025:x.value2024?Number((((x.value2025-x.value2024)/x.value2024)*100).toFixed(2)):null}))}
async function fetchText(url){const r=await fetch(url,{headers:{'User-Agent':'SIGES-Escola-Segura/3.5 public-source-reader'}});if(!r.ok)throw new Error(`Fonte externa respondeu HTTP ${r.status}`);return await r.text()}
function htmlToText(html){return decode(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p>|<\/div>|<\/tr>|<\/li>/gi,'\n'))}
async function loadCbvj(){if(cache.cbvj&&cache.cbvj.expiresAt>Date.now())return cache.cbvj.data;const text=htmlToText(await fetchText(CBVJ_2025_URL));const text24=await fetchText(CBVJ_2024_URL).catch(()=>null);const corridors=normalizeRanking(parseRanking(text));const data={source:'CBVJ',sourceName:'Corpo de Bombeiros Voluntários de Joinville',municipality:'Joinville',retrievedAt:new Date().toISOString(),latestCompleteYear:2025,latestPublicationDate:'2026-01-08',methodology:'Ranking publicado no Relatório Operacional 2025/CBVJ; o SIGES preserva a fonte e não substitui dados históricos de outras publicações.',urls:{2025:CBVJ_2025_URL,2024:CBVJ_2024_URL},summary:{totalOccurrences2025:14574,trafficCarVsMotorcycle2025:1923},corridors,raw:{ranking2025Count:corridors.length,has2024Publication:Boolean(text24)}};cache.cbvj={data,expiresAt:Date.now()+21600000};return data}
function extractRoad(title){let s=clean(title.replace(/^Estudo Técnico(?: Redutor de Velocidade 40 kmh| Controlador de Velocidade 60km\/h| Controlador de Velocidade Semafórico)?\s*/i,''));const m=s.match(/(?:Rua|Av\.?|Avenida|Rodovia|BR-)[^,–]+/i);if(!m)return'Outros';s=m[0].replace(/\s+\d+[\wºª.-]*(?:\s*(?:e|,|\/|com|próx\.?|prox\.?|nº?|n°).*)?$/i,'');return clean(s).replace(/\s+(?:N-S|S-N|L-O|O-L)$/i,'')||clean(m[0])}
function parseDetrans(html){const items=[];const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>([\s\S]{0,900}?)(?=<a\s|<\/section|$)/gi;let m;while((m=re.exec(html))){const title=decode(m[2]);if(!/Estudo Técnico|Atualização Bienal/i.test(title))continue;const tail=decode(m[3]);const dateMatch=tail.match(/Documento disponibilizado em\s*(\d{2}\/\d{2}\/\d{4})/i);items.push({title,url:new URL(m[1],DETRANS_URL).href,date:dateMatch?dateMatch[1]:null,year:dateMatch?Number(dateMatch[1].slice(-4)):null,road:extractRoad(title)})}const unique=[];const seen=new Set();for(const x of items){if(!seen.has(x.url)){seen.add(x.url);unique.push(x)}}const years={};for(const x of unique){const y=x.year||'indefinido';years[y]=(years[y]||0)+1}const corridors={};for(const x of unique){if(x.road&&x.road!=='Outros')corridors[x.road]=(corridors[x.road]||0)+1}const ranking=Object.entries(corridors).map(([road,count])=>({road,count})).sort((a,b)=>b.count-a.count).map((x,i)=>({...x,rank:i+1}));const latestYear=Math.max(...unique.map(x=>x.year||0));const latestDate=unique.map(x=>x.date).filter(Boolean).sort((a,b)=>b.split('/').reverse().join('').localeCompare(a.split('/').reverse().join('')))[0]||null;return{source:'DETRANS',sourceName:'Departamento de Trânsito de Joinville',municipality:'Joinville',retrievedAt:new Date().toISOString(),latestCompleteYear:latestYear||null,latestPublicationDate:latestDate?latestDate.split('/').reverse().join('-'):null,methodology:'Inventário somente leitura dos estudos técnicos publicados oficialmente pelo DETRANS. O ranking representa quantidade de estudos por corredor, não acidentes. Não se calcula variação 2024→2025 quando a fonte não fornece série anual homogênea.',urls:{publication:DETRANS_URL},summary:{totalOccurrences:null,totalStudies:unique.length,studiesByYear:years},corridors:ranking,documents:unique.slice(0,120)}}
async function loadDetrans(){if(cache.detrans&&cache.detrans.expiresAt>Date.now())return cache.detrans.data;const data=parseDetrans(await fetchText(DETRANS_URL));cache.detrans={data,expiresAt:Date.now()+21600000};return data}
async function getJson(url){const r=await fetch(url,{headers:{'User-Agent':'SIGES-Escola-Segura/3.5 simgeo-reader'}});if(!r.ok)throw new Error(`SIMGeo respondeu HTTP ${r.status}`);return r.json()}
async function loadSimgeo(){if(cache.simgeo&&cache.simgeo.expiresAt>Date.now())return cache.simgeo.data;const [schools,layersJson]=await Promise.all([getJson(`${SIMGEO_SCHOOLS}/query?where=1%3D1&returnCountOnly=true&f=json`),getJson(`${SIMGEO_ROOT}/planejamento/MapServer/layers?f=json`)]);const layers=(layersJson.layers||[]).map(x=>({id:x.id,name:x.name,type:x.type}));const data={source:'SIMGEO',sourceName:'Sistema de Informações Municipais Georreferenciadas',municipality:'Joinville',retrievedAt:new Date().toISOString(),latestCompleteYear:null,latestPublicationDate:null,methodology:'Leitura somente consulta das camadas públicas do SIMGeo. Quantidades são inventário de dados, não ocorrência de sinistros. A georreferência é usada para qualificar proximidade e território; não altera a fonte original.',urls:{portal:SIMGEO_URL,rest:SIMGEO_ROOT,schools:SIMGEO_SCHOOLS,roads:SIMGEO_ROADS,cycle:SIMGEO_CYCLE},summary:{totalOccurrences:null,schoolUnits:schools.count??null,planningLayers:layers.length},corridors:[],layers,privacy:'Somente metadados e contagens agregadas; nenhuma alteração de camada é realizada pelo SIGES.'};cache.simgeo={data,expiresAt:Date.now()+21600000};return data}
function ptGeom(feature){return feature?.geometry?.x!=null&&feature?.geometry?.y!=null?feature.geometry:null}
function distancePointSegment(px,py,ax,ay,bx,by){const dx=bx-ax,dy=by-ay;if(dx===0&&dy===0)return Math.hypot(px-ax,py-ay);const t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy)));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy))}
function distancePointPolyline(p,paths){let best=Infinity;for(const path of paths||[])for(let i=1;i<path.length;i++)best=Math.min(best,distancePointSegment(p.x,p.y,path[i-1][0],path[i-1][1],path[i][0],path[i][1]));return best}
function esc(v){return String(v||'').replace(/'/g,"''")}
async function nearby(url,point,distance,outFields){const params=new URLSearchParams({where:'1=1',geometry:JSON.stringify({x:point.x,y:point.y,spatialReference:{wkid:31982}}),geometryType:'esriGeometryPoint',inSR:'31982',spatialRel:'esriSpatialRelIntersects',distance:String(distance),units:'esriSRUnit_Meter',outFields,returnGeometry:'true',outSR:'31982',f:'json',resultRecordCount:'50'});const j=await getJson(`${url}/query?${params}`);return j.features||[]}
async function schoolFeatures(name){const where=name?`escola='${esc(name)}'`:'1=1';const j=await getJson(`${SIMGEO_SCHOOLS}/query?${new URLSearchParams({where,outFields:'objectid,escola,endereço',returnGeometry:'true',outSR:'31982',f:'json',resultRecordCount:'2000'})}`);return j.features||[]}
async function correlateSchool(feature){const p=ptGeom(feature);if(!p)return null;const attrs=feature.attributes||{};const [roads,cycles]=await Promise.all([nearby(SIMGEO_ROADS,p,100,'nmlogradourocompleto,legenda_logradouro,codlogra'),nearby(SIMGEO_CYCLE,p,150,'nome_logra,ciclo,extensao,categoria')]);const roadDistances=roads.map(f=>({name:f.attributes?.nmlogradourocompleto||'',distanceM:Number(distancePointPolyline(p,f.geometry?.paths||[]).toFixed(1)),status:f.attributes?.legenda_logradouro||''})).filter(x=>Number.isFinite(x.distanceM)).sort((a,b)=>a.distanceM-b.distanceM);const cycleDistances=cycles.map(f=>({name:f.attributes?.nome_logra||'',type:f.attributes?.ciclo||'',category:f.attributes?.categoria||'',distanceM:Number(distancePointPolyline(p,f.geometry?.paths||[]).toFixed(1)),extensionM:f.attributes?.extensao||null})).filter(x=>Number.isFinite(x.distanceM)).sort((a,b)=>a.distanceM-b.distanceM);return{objectId:attrs.objectid,name:attrs.escola,address:attrs['endereço'],coordinates:{x:p.x,y:p.y,spatialReference:31982},nearestRoad:roadDistances[0]||null,nearbyRoads:roadDistances.slice(0,5),cycleWithin150m:cycleDistances.length>0,nearestCycle:cycleDistances[0]||null,nearbyCycles:cycleDistances.slice(0,10),methodology:'Correlação espacial SIMGeo: ponto oficial da unidade escolar, distância euclidiana em SIRGAS 2000 / UTM 22S (EPSG:31982) até feições lineares retornadas pelo SIMGeo. Distância não equivale a rota de caminhada.'}}
async function loadSpatialSchool(name){const key=name||'__all__';if(cache.spatial?.[key]&&cache.spatial[key].expiresAt>Date.now())return cache.spatial[key].data;cache.spatial=cache.spatial||{};const features=await schoolFeatures(name);if(!features.length)throw new Error('Unidade escolar não encontrada no SIMGeo.');const result=[];for(let i=0;i<features.length;i+=6){const chunk=features.slice(i,i+6);const rows=await Promise.all(chunk.map(correlateSchool));result.push(...rows.filter(Boolean))}const data={source:'SIMGEO',sourceName:'Correlação espacial escolar',municipality:'Joinville',retrievedAt:new Date().toISOString(),count:result.length,results:result,thresholds:{roadM:100,cycleM:150},readOnly:true};cache.spatial[key]={data,expiresAt:Date.now()+21600000};return data}
module.exports=function buildPublicSourcesRouter(){const router=express.Router();router.get('/health',(req,res)=>res.json({ok:true,source:'public-sources',mode:'read-only'}));router.get('/cbvj',async(req,res)=>{try{res.json(await loadCbvj())}catch(error){res.status(502).json({error:'Não foi possível consultar o CBVJ agora.',detail:error.message,source:'CBVJ',readOnly:true})}});router.get('/detrans',async(req,res)=>{try{res.json(await loadDetrans())}catch(error){res.status(502).json({error:'Não foi possível consultar o DETRANS agora.',detail:error.message,source:'DETRANS',readOnly:true})}});router.get('/simgeo',async(req,res)=>{try{res.json(await loadSimgeo())}catch(error){res.status(502).json({error:'Não foi possível consultar o SIMGeo agora.',detail:error.message,source:'SIMGEO',readOnly:true})}});router.get('/spatial/school',async(req,res)=>{try{res.json(await loadSpatialSchool(req.query.name||null))}catch(error){res.status(502).json({error:'Não foi possível calcular a correlação espacial agora.',detail:error.message,source:'SIMGEO',readOnly:true})}});return router}
module.exports.constants={CBVJ_2025_URL,CBVJ_2024_URL,DETRANS_URL,SIMGEO_URL,SIMGEO_ROOT,SIMGEO_SCHOOLS,SIMGEO_ROADS,SIMGEO_CYCLE};