const express=require('express');

const CBVJ_2025_URL='https://www.cbvj.org.br/blog/bombeiros-voluntarios-de-joinville-atenderam-14-574-ocorrencias-em-2025/';
const CBVJ_2024_URL='https://www.cbvj.org.br/blog/bombeiros-voluntarios-de-joinville-atenderam-mais-de-11-mil-ocorrencias-em-2024/';
const DETRANS_URL='https://www.joinville.sc.gov.br/publicacoes/estudos-tecnicos-equipamentos-de-fiscalizacao-eletronica-radares-e-lombadas/';
const SIMGEO_URL='https://www.joinville.sc.gov.br/servicos/acessar-sistema-de-informacoes-municipais-georreferenciadas-simgeo/';
const SIMGEO_ROOT='https://geo.joinville.sc.gov.br/server/rest/services/simgeo';
const SIMGEO_SCHOOLS='https://geo.joinville.sc.gov.br/server/rest/services/SEPUR/educacao_simgeo_v4/MapServer/1';
let cache={};
function clean(v){return String(v||'').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim()}
function decode(v){return clean(String(v||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&ndash;/g,'–').replace(/&nbsp;/g,' '))}
function number(v){const n=Number(String(v||'').replace(/\./g,'').replace(',','.'));return Number.isFinite(n)?n:null}
function parseRanking(text){const out=[];const block=text.match(/Ranking[^\n]{0,120}As dez vias com mais acidentes([\s\S]{0,3000}?)(?:Operacional|Fonte:)/i);if(!block)return out;for(const row of block[1].split(/\n+/).map(clean).filter(Boolean)){const m=row.match(/^(?:\d+º?\s*\|\s*)?(?:Rua|Avenida|Av\.?|Rodovia|BR-)?\s*([^|]+?)\s*\|\s*(\d+)\s*\|\s*(?:Rua|Avenida|Av\.?|Rodovia|BR-)?\s*([^|]+?)\s*\|\s*(\d+)$/i);if(m)out.push({road:clean(m[1]),value2024:number(m[2]),road2025:clean(m[3]),value2025:number(m[4])})}return out}
function normalizeRanking(rows){const map=new Map();for(const r of rows){const road=clean(r.road2025||r.road);if(road)map.set(road.toLowerCase(),{road,value2024:r.value2024,value2025:r.value2025})}return[...map.values()].sort((a,b)=>(b.value2025||0)-(a.value2025||0)).map((x,i)=>({...x,rank2025:i+1,variation2024to2025:x.value2024?Number((((x.value2025-x.value2024)/x.value2024)*100).toFixed(2)):null}))}
async function fetchText(url){const r=await fetch(url,{headers:{'User-Agent':'SIGES-Escola-Segura/3.4 public-source-reader'}});if(!r.ok)throw new Error(`Fonte externa respondeu HTTP ${r.status}`);return await r.text()}
function htmlToText(html){return decode(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p>|<\/div>|<\/tr>|<\/li>/gi,'\n'))}
async function loadCbvj(){if(cache.cbvj&&cache.cbvj.expiresAt>Date.now())return cache.cbvj.data;const text=htmlToText(await fetchText(CBVJ_2025_URL));const text24=await fetchText(CBVJ_2024_URL).catch(()=>null);const corridors=normalizeRanking(parseRanking(text));const data={source:'CBVJ',sourceName:'Corpo de Bombeiros Voluntários de Joinville',municipality:'Joinville',retrievedAt:new Date().toISOString(),latestCompleteYear:2025,latestPublicationDate:'2026-01-08',methodology:'Ranking publicado no Relatório Operacional 2025/CBVJ; o SIGES preserva a fonte e não substitui dados históricos de outras publicações.',urls:{2025:CBVJ_2025_URL,2024:CBVJ_2024_URL},summary:{totalOccurrences2025:14574,trafficCarVsMotorcycle2025:1923},corridors,raw:{ranking2025Count:corridors.length,has2024Publication:Boolean(text24)}};cache.cbvj={data,expiresAt:Date.now()+21600000};return data}
function parseDetrans(html){const text=htmlToText(html);const items=[];const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const title=decode(m[2]);if(!/Estudo Técnico|Atualização Bienal/i.test(title))continue;const pos=text.indexOf(title);const before=pos>=0?text.slice(Math.max(0,pos-260),pos):'';const dateMatch=before.match(/(?:Documento disponibilizado em|disponibilizado em)\s*(\d{2}\/\d{2}\/\d{4})/i);items.push({title,url:new URL(m[1],DETRANS_URL).href,date:dateMatch?dateMatch[1]:null})}const unique=[];const seen=new Set();for(const x of items){if(!seen.has(x.url)){seen.add(x.url);unique.push(x)}}const years={};for(const x of unique){const y=x.date?x.date.slice(-4):'indefinido';years[y]=(years[y]||0)+1}const corridors={};for(const x of unique){const mm=x.title.match(/(?:Rua|Av\.?|Avenida)\s+([^,–]+)/i);const road=clean(mm?.[1]||'Outros');if(road&&road!=='Outros')corridors[road]=(corridors[road]||0)+1}const ranking=Object.entries(corridors).map(([road,count])=>({road,count})).sort((a,b)=>b.count-a.count).map((x,i)=>({...x,rank:i+1}));return{source:'DETRANS',sourceName:'Departamento de Trânsito de Joinville',municipality:'Joinville',retrievedAt:new Date().toISOString(),latestCompleteYear:2026,latestPublicationDate:'2026-08-27',methodology:'Inventário somente leitura dos estudos técnicos publicados oficialmente pelo DETRANS. O ranking representa quantidade de estudos por corredor, não acidentes. Não se calcula variação 2024→2025 quando a fonte não fornece série anual homogênea.',urls:{publication:DETRANS_URL},summary:{totalOccurrences:null,totalStudies:unique.length,studiesByYear:years},corridors:ranking,documents:unique.slice(0,120)}}
async function loadDetrans(){if(cache.detrans&&cache.detrans.expiresAt>Date.now())return cache.detrans.data;const data=parseDetrans(await fetchText(DETRANS_URL));cache.detrans={data,expiresAt:Date.now()+21600000};return data}
async function getJson(url){const r=await fetch(url,{headers:{'User-Agent':'SIGES-Escola-Segura/3.4 simgeo-reader'}});if(!r.ok)throw new Error(`SIMGeo respondeu HTTP ${r.status}`);return r.json()}
async function loadSimgeo(){if(cache.simgeo&&cache.simgeo.expiresAt>Date.now())return cache.simgeo.data;const [schools,layersJson]=await Promise.all([getJson(`${SIMGEO_SCHOOLS}/query?where=1%3D1&returnCountOnly=true&f=json`),getJson(`${SIMGEO_ROOT}/planejamento/MapServer/layers?f=json`)]);const layers=(layersJson.layers||[]).map(x=>({id:x.id,name:x.name,type:x.type}));const data={source:'SIMGEO',sourceName:'Sistema de Informações Municipais Georreferenciadas',municipality:'Joinville',retrievedAt:new Date().toISOString(),latestCompleteYear:null,latestPublicationDate:null,methodology:'Leitura somente consulta das camadas públicas do SIMGeo. Quantidades são inventário de dados, não ocorrência de sinistros. A georreferência é usada para qualificar proximidade e território; não altera a fonte original.',urls:{portal:SIMGEO_URL,rest:SIMGEO_ROOT,schools:SIMGEO_SCHOOLS},summary:{totalOccurrences:null,schoolUnits:schools.count??null,planningLayers:layers.length},corridors:[],layers,privacy:'Somente metadados e contagens agregadas; nenhuma alteração de camada é realizada pelo SIGES.'};cache.simgeo={data,expiresAt:Date.now()+21600000};return data}
module.exports=function buildPublicSourcesRouter(){const router=express.Router();router.get('/health',(req,res)=>res.json({ok:true,source:'public-sources',mode:'read-only'}));router.get('/cbvj',async(req,res)=>{try{res.json(await loadCbvj())}catch(error){res.status(502).json({error:'Não foi possível consultar o CBVJ agora.',detail:error.message,source:'CBVJ',readOnly:true})}});router.get('/detrans',async(req,res)=>{try{res.json(await loadDetrans())}catch(error){res.status(502).json({error:'Não foi possível consultar o DETRANS agora.',detail:error.message,source:'DETRANS',readOnly:true})}});router.get('/simgeo',async(req,res)=>{try{res.json(await loadSimgeo())}catch(error){res.status(502).json({error:'Não foi possível consultar o SIMGeo agora.',detail:error.message,source:'SIMGEO',readOnly:true})}});return router}
module.exports.constants={CBVJ_2025_URL,CBVJ_2024_URL,DETRANS_URL,SIMGEO_URL,SIMGEO_ROOT,SIMGEO_SCHOOLS};