"use client";
import Link from "next/link";
import {ArrowLeft,BookOpen,CheckCircle2,FileCheck,History,LockKeyhole,Printer,Scale,ShieldCheck} from "lucide-react";

const rules=[
 ["01","Unidade de análise","Cada escola é tratada como unidade territorial; indicadores municipais são contexto, não substituto da mensuração local."],
 ["02","500 m analítico","O raio de 500 m é parâmetro de triagem geográfica. Não é área legal de influência da escola."],
 ["03","Fonte ≠ inferência","Fonte oficial, geoprocessamento, campo, histórico e indicador derivado são identificados separadamente."],
 ["04","Ausência ≠ zero","Campo não localizado permanece como não informado. O sistema não converte lacuna em segurança."],
 ["05","Acidentes com vítimas","Quando a camada municipal assim define, o SIGES usa a expressão acidentes com vítimas; não transforma o campo em total de acidentes."],
 ["06","Velocidade","Velocidade observada em pesquisa não é apresentada como velocidade regulamentada sem fonte específica."],
 ["07","Decisão técnica","Prioridade SIGES orienta triagem. Engenharia, fiscalização e medidas viárias exigem validação competente e de campo."],
 ["08","Dados individuais","Avaliações do Aluno Guia são separadas da leitura territorial e devem permanecer protegidas por controle de acesso."],
];

export default function Governanca(){return <main className="min-h-screen p-4 md:p-8 max-w-[1500px] mx-auto"><header className="mb-6"><Link href="/estrategia" className="muted text-sm flex items-center gap-2 mb-3"><ArrowLeft size={15}/> Centro Estratégico</Link><div className="text-cyan-300 text-xs font-bold tracking-[.2em]">SIGES • GOVERNANÇA</div><h1 className="text-3xl md:text-5xl font-black mt-1">Metodologia, auditoria e documentos</h1><p className="muted mt-2 max-w-4xl">Camada institucional para garantir que cada número utilizado em negociação possa ser explicado, rastreado e reavaliado.</p></header>
 <div className="grid lg:grid-cols-[1.2fr_.8fr] gap-5"><section className="card p-5"><div className="flex items-center gap-2"><ShieldCheck size={19} className="text-cyan-300"/><h2 className="text-2xl font-black">Regras de integridade</h2></div><div className="space-y-3 mt-5">{rules.map(([n,t,d])=><article key={n} className="flex gap-4 border-b border-[#1f3347] pb-4"><span className="text-cyan-300 font-black">{n}</span><div><h3 className="font-bold">{t}</h3><p className="muted text-sm leading-6 mt-1">{d}</p></div></article>)}</div></section><aside className="space-y-5"><section className="card p-5"><div className="flex gap-2 font-bold"><History size={18} className="text-cyan-300"/> Versionamento</div><div className="space-y-3 mt-4 text-sm"><div><span className="muted block text-xs">MATRIZ</span><b>HSI-DOTH-P Escolar 3.2</b></div><div><span className="muted block text-xs">PROCESSO</span><b>Fonte → tratamento → indicador → recomendação</b></div><div><span className="muted block text-xs">REVISÃO</span><b>Registrar data e versão a cada atualização</b></div></div></section><section className="card p-5"><div className="flex gap-2 font-bold"><LockKeyhole size={18} className="text-cyan-300"/> Proteção</div><p className="muted text-sm leading-6 mt-3">Dados individuais do Aluno Guia não entram no painel público territorial. Relatórios externos devem utilizar agregados ou pseudonimização.</p></section><section className="card p-5"><div className="flex gap-2 font-bold"><Scale size={18} className="text-cyan-300"/> Limite institucional</div><p className="muted text-sm leading-6 mt-3">O SIGES é ferramenta de inteligência e preparação técnica. Não cria obrigação administrativa nem substitui competência legal dos órgãos públicos.</p></section></aside></div>
 <section className="card p-5 mt-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="flex gap-2 items-center font-bold"><FileCheck size={18} className="text-cyan-300"/> Relatório institucional</div><p className="muted text-sm mt-1">Use a impressão do navegador para gerar PDF do conteúdo desta camada, preservando data e contexto.</p></div><button onClick={()=>window.print()} className="card px-4 py-3 flex items-center gap-2"><Printer size={16}/> Imprimir / PDF</button></div></section>
 <section className="card p-5 mt-5"><div className="flex gap-2 items-center font-bold"><BookOpen size={18} className="text-cyan-300"/> Estrutura documental recomendada</div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-4">{["Sumário executivo","Metodologia e limitações","Dossiês por escola","Plano e indicadores de resultado"].map((x,i)=><div className="bg-[#091624] rounded-xl p-4" key={x}><div className="text-cyan-300 text-xs font-black">0{i+1}</div><strong className="block mt-2">{x}</strong></div>)}</div></section>
 <section className="card p-4 mt-5"><div className="flex gap-2 items-center text-sm"><CheckCircle2 size={17} className="text-cyan-300"/><span>Para uma negociação técnica, o pacote mínimo deve conter: evidências → dossiês → solução → cenário de projeto → indicadores de resultado → metodologia e limitações.</span></div></section>
 </main>}
