"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BookOpen,ExternalLink,Database} from "lucide-react";
import {supabase} from "@/lib/supabase";

type Row={metric_key:string;metric_label:string;value_numeric:number|null;value_text:string|null;unit:string|null;category:string;notes:string|null;source_url:string|null;source_date:string|null};
const fmt=(r:Row)=>r.value_numeric!==null&&r.value_numeric!==undefined?`${r.value_numeric}${r.unit?` ${r.unit}`:""}`:(r.value_text||"Não informado");

export default function CidadeEmDados(){
 const [rows,setRows]=useState<Row[]>([]);const [cat,setCat]=useState("TODAS");const [q,setQ]=useState("");
 useEffect(()=>{supabase().from("city_data_context").select("*").order("category").order("metric_label").then(({data})=>setRows((data as Row[])||[]))},[]);
 const cats=useMemo(()=>["TODAS",...Array.from(new Set(rows.map(r=>r.category)))],[rows]);
 const filtered=useMemo(()=>rows.filter(r=>(cat==="TODAS"||r.category===cat)&&`${r.metric_label} ${r.category} ${r.notes||""}`.toLowerCase().includes(q.toLowerCase())),[rows,cat,q]);
 return <main className="min-h-screen p-4 md:p-8 max-w-[1500px] mx-auto"><div className="mb-6"><Link href="/" className="muted text-sm flex items-center gap-2"><ArrowLeft size={15}/> Dashboard</Link><div className="text-cyan-300 text-xs font-bold tracking-widest mt-4">SIGES • CONTEXTO MUNICIPAL</div><h1 className="text-3xl md:text-4xl font-black mt-1">Joinville Cidade em Dados 2025</h1><p className="muted mt-2 max-w-4xl">Base contextual incorporada ao SIGES para qualificar a leitura territorial das escolas, mobilidade, transporte, segurança viária e educação para o trânsito. Os indicadores municipais não substituem a mensuração específica do entorno escolar.</p></div><section className="card p-5 mb-5"><div className="flex items-center gap-2 font-bold"><BookOpen size={18} className="text-cyan-300"/> Fonte oficial</div><p className="muted text-sm mt-2">Prefeitura de Joinville · Joinville Cidade em Dados 2025 · Ambiente Construído. Documento disponibilizado em 19/12/2025.</p><a href="https://www.joinville.sc.gov.br/publicacoes/joinville-cidade-em-dados-2025/" target="_blank" rel="noreferrer" className="text-cyan-300 text-sm inline-flex items-center gap-1 mt-3">Abrir publicação oficial <ExternalLink size={14}/></a></section><section className="card p-4 mb-5"><div className="grid lg:grid-cols-[1fr_auto] gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar indicador..." className="bg-[#07111f] rounded-xl px-4 py-3 outline-none"/><select value={cat} onChange={e=>setCat(e.target.value)} className="bg-[#07111f] rounded-xl px-4 py-3">{cats.map(c=><option key={c}>{c}</option>)}</select></div></section><section className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(r=><article className="card p-5" key={r.metric_key}><div className="muted text-xs">{r.category}</div><h2 className="font-bold mt-2 leading-snug">{r.metric_label}</h2><div className="text-2xl font-black mt-4">{fmt(r)}</div><p className="muted text-xs mt-3">Ano do dado: {r.source_date?new Date(r.source_date).getFullYear():"—"} · fonte oficial municipal</p>{r.notes&&<p className="muted text-xs mt-2 leading-5">{r.notes}</p>}</article>)}</section>{!filtered.length&&<div className="card p-8 text-center muted"><Database className="mx-auto mb-2"/>Nenhum indicador encontrado.</div>}<footer className="muted text-xs mt-6">Uso analítico no SIGES. Indicadores municipais são contexto; decisões de engenharia e implantação de medidas escolares exigem validação específica da unidade e dos órgãos competentes.</footer></main>;
}
