"use client";
import{useEffect,useMemo,useState}from"react";
import Link from"next/link";
import{ArrowLeft,Save,Target,Users}from"lucide-react";
import{supabase}from"@/lib/supabase";

type Unit={id:string;name:string;rank:number;territorial_priority:string|null;ipe_territorial:number|null;hsi:number|null;territorial_confidence:string|null};
type Project={id:string;name:string;objective:string|null;solution_type:string;status:string;school_count:number;phase_count:number;estimated_cost:number|null;baseline:unknown;targets:unknown};
type Baseline={schools:number;p1:number;p2:number;avg_hsi:number|null;avg_ipe_territorial:number|null;average_confidence:string|null;measurement_stage:string};

const priority=(value:string|null|undefined):"P1"|"P2"|"P3"|"P4"=>value?.startsWith("P1")?"P1":value?.startsWith("P2")?"P2":value?.startsWith("P3")?"P3":"P4";
const average=(values:Array<number|null|undefined>):number|null=>{const valid=values.filter((value):value is number=>value!=null&&!Number.isNaN(Number(value))).map(Number);return valid.length?Number((valid.reduce((a,b)=>a+b,0)/valid.length).toFixed(2)):null};
const confidence=(units:Unit[]):string|null=>{const values=units.map(unit=>unit.territorial_confidence).filter((value):value is string=>!!value);if(!values.length)return null;const order=["ALTA","MEDIA","BAIXA"];return order.find(value=>values.includes(value))??values[0]};

export default function Projeto(){
 const[units,setUnits]=useState<Unit[]>([]),[selected,setSelected]=useState<string[]>([]),[projects,setProjects]=useState<Project[]>([]),[name,setName]=useState("Projeto Piloto SIGES — Segurança Escolar"),[objective,setObjective]=useState("Validar um modelo integrado de diagnóstico, intervenção e mensuração da segurança no entorno escolar."),[solution,setSolution]=useState("ALUNO_GUIA"),[months,setMonths]=useState(4),[cost,setCost]=useState(""),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[loadError,setLoadError]=useState("");
 const load=async()=>{setLoadError("");const[u,r]=await Promise.all([supabase().from("units").select("id,name,rank,territorial_priority,ipe_territorial,hsi,territorial_confidence").order("ipe_territorial",{ascending:false}),supabase().from("strategy_projects").select("*").order("created_at",{ascending:false})]);if(u.error)setLoadError(u.error.message);setUnits((u.data??[]) as Unit[]);if(r.error)setLoadError(r.error.message);setProjects((r.data??[]) as Project[])};
 useEffect(()=>{void load()},[]);
 const priorityUnits=useMemo(()=>units.filter(unit=>["P1","P2"].includes(priority(unit.territorial_priority))),[units]);
 const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
 const selectP1=()=>setSelected(units.filter(unit=>priority(unit.territorial_priority)==="P1").map(unit=>unit.id));
 const selectP12=()=>setSelected(priorityUnits.map(unit=>unit.id));
 const baseline=useMemo<Baseline>(()=>{const chosen=units.filter(unit=>selected.includes(unit.id));return{schools:chosen.length,p1:chosen.filter(unit=>priority(unit.territorial_priority)==="P1").length,p2:chosen.filter(unit=>priority(unit.territorial_priority)==="P2").length,avg_hsi:average(chosen.map(unit=>unit.hsi)),avg_ipe_territorial:average(chosen.map(unit=>unit.ipe_territorial)),average_confidence:confidence(chosen),measurement_stage:"T0_BASELINE"}},[units,selected]);
 const save=async()=>{if(!name.trim()||!selected.length){setMessage("Informe o nome e selecione pelo menos uma escola.");return}setSaving(true);setMessage("");const phaseCount=Math.max(3,months);const estimatedCost=cost.trim()?Number(cost.replace(",",".")):null;const payload={name:name.trim(),objective:objective.trim(),solution_type:solution,status:"DRAFT",school_count:selected.length,phase_count:phaseCount,estimated_cost:Number.isFinite(estimatedCost)?estimatedCost:null,baseline,targets:{measurement_stage:"T2_POS_INTERVENCAO",target_ipe_improvement:null,target_hsi_improvement:null,notes:"Metas quantitativas devem ser definidas após validação do baseline; não são preenchidas automaticamente."},deliverables:["Diagnóstico territorial","Plano de intervenção","Registro de execução","Reavaliação T1/T2"],assumptions:["Validação de campo","Disponibilidade institucional"],risks:["Dados incompletos","Mudança de contexto territorial"]};const{data,error}=await supabase().from("strategy_projects").insert(payload).select().single();if(error){setMessage(`Erro ao salvar: ${error.message}`);setSaving(false);return}if(!data?.id){setMessage("Erro ao salvar: o projeto não retornou um identificador.");setSaving(false);return}const projectId=String(data.id);const links=selected.map(unit_id=>({project_id:projectId,unit_id,role:priority(units.find(unit=>unit.id===unit_id)?.territorial_priority)==="P1"?"PRIORIDADE_CRITICA":"PRIORIDADE_ALTA"}));const{error:linkError}=await supabase().from("strategy_project_units").insert(links);if(linkError){setMessage(`Projeto criado, mas houve erro ao vincular escolas: ${linkError.message}`);setSaving(false);void load();return}setMessage("Projeto criado com sucesso.");setSaving(false);void load()};
 return <main className="min-h-screen p-4 md:p-8 max-w-[1500px] mx-auto"><Link href="/estrategia" className="muted text-sm flex gap-2 items-center mb-4"><ArrowLeft size={15}/> Centro Estratégico</Link><header className="mb-6"><div className="text-cyan-300 text-xs font-bold tracking-[.22em]">SIGES 3.5 • PROJETO</div><h1 className="text-3xl md:text-5xl font-black mt-1">Simulador de Projeto</h1><p className="muted mt-2 max-w-4xl">Transforme escolas prioritárias em um projeto técnico persistente. O sistema registra a seleção, o baseline e as metas como objetos de projeto; não inventa resultados.</p></header>{loadError&&<div className="card p-4 mb-4 text-red-300">Erro de leitura: {loadError}</div>}
 <section className="grid lg:grid-cols-[1.1fr_.9fr] gap-5"><div className="card p-5"><div className="flex items-center gap-2 font-bold mb-4"><Target size={18} className="text-cyan-300"/> 1. Definição</div><label className="muted text-xs">NOME</label><input value={name} onChange={event=>setName(event.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"/><label className="muted text-xs">OBJETIVO</label><textarea value={objective} onChange={event=>setObjective(event.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3 min-h-24"/><label className="muted text-xs">SOLUÇÃO PRINCIPAL</label><select value={solution} onChange={event=>setSolution(event.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"><option value="ALUNO_GUIA">Aluno Guia</option><option value="ENAT_NEUROEDUCACAO">ENAT — Neuroeducação</option><option value="MENSURACAO_SIGES">Mensuração SIGES</option><option value="PLANO_CIRCULACAO">Plano de Circulação Escolar</option><option value="MONITORAMENTO">Monitoramento</option></select><div className="grid grid-cols-2 gap-3"><div><label className="muted text-xs">DURAÇÃO (MESES)</label><input type="number" min="1" max="24" value={months} onChange={event=>setMonths(Number(event.target.value))} className="w-full mt-1 bg-[#07111f] rounded-xl p-3"/></div><div><label className="muted text-xs">CUSTO ESTIMADO (OPCIONAL)</label><input value={cost} onChange={event=>setCost(event.target.value)} placeholder="R$" className="w-full mt-1 bg-[#07111f] rounded-xl p-3"/></div></div></div>
 <aside className="card p-5"><div className="flex items-center gap-2 font-bold mb-4"><Users size={18} className="text-cyan-300"/> 2. Selecionar escolas</div><div className="flex gap-2 mb-4"><button onClick={selectP1} className="px-3 py-2 rounded-xl bg-[#102337] text-sm">Selecionar P1</button><button onClick={selectP12} className="px-3 py-2 rounded-xl bg-[#102337] text-sm">Selecionar P1+P2</button><button onClick={()=>setSelected([])} className="px-3 py-2 rounded-xl bg-[#07111f] text-sm">Limpar</button></div><div className="max-h-[430px] overflow-auto space-y-2">{priorityUnits.map(unit=><button key={unit.id} onClick={()=>toggle(unit.id)} className={`w-full text-left rounded-xl p-3 border ${selected.includes(unit.id)?"border-cyan-400 bg-cyan-950/20":"border-[#20354a] bg-[#07111f]"}`}><div className="flex justify-between gap-2"><span className="font-semibold">{unit.name}</span><span className="text-xs font-bold">{priority(unit.territorial_priority)}</span></div><div className="muted text-xs mt-1">IPE {unit.ipe_territorial??"—"} · HSI {unit.hsi??"—"}</div></button>)}</div><div className="mt-4 font-bold">{selected.length} escola(s) selecionada(s)</div></aside></section>
 <section className="grid md:grid-cols-3 gap-4 mt-5"><div className="card p-5"><div className="muted text-xs">T0 • BASELINE</div><div className="text-3xl font-black mt-1">{baseline.schools}</div><div className="muted text-sm">escolas</div><div className="mt-3 text-sm">P1: <b>{baseline.p1}</b> · P2: <b>{baseline.p2}</b><br/>HSI médio: <b>{baseline.avg_hsi??"—"}</b><br/>IPE territorial médio: <b>{baseline.avg_ipe_territorial??"—"}</b><br/>Confiança: <b>{baseline.average_confidence??"—"}</b></div></div><div className="card p-5"><div className="muted text-xs">FASES</div><div className="text-3xl font-black mt-1">{Math.max(3,months)}</div><div className="muted text-sm">fases sugeridas</div><div className="mt-3 text-sm">1. Diagnóstico<br/>2. Preparação<br/>3. Intervenção<br/>4. T1/T2 conforme duração</div></div><div className="card p-5"><div className="muted text-xs">META</div><div className="text-lg font-bold mt-1">Definição após T0</div><div className="muted text-sm mt-2">O SIGES não cria metas de melhoria sem baseline validado. Elas serão registradas no projeto.</div></div></section>
 <div className="flex justify-end mt-5"><button onClick={()=>void save()} disabled={saving} className="px-5 py-3 rounded-xl bg-cyan-800 hover:bg-cyan-700 font-bold flex gap-2 items-center disabled:opacity-50"><Save size={17}/>{saving?"Salvando...":"Criar projeto"}</button></div>{message&&<div className="card p-4 mt-4">{message}</div>}
 <section className="mt-8"><h2 className="text-2xl font-black mb-3">Projetos registrados</h2>{projects.length===0?<div className="card p-5 muted">Nenhum projeto criado.</div>:<div className="grid md:grid-cols-2 gap-3">{projects.map(project=><div className="card p-4" key={project.id}><div className="flex justify-between"><b>{project.name}</b><span className="text-xs">{project.status}</span></div><div className="muted text-sm mt-2">{project.school_count} escolas · {project.phase_count} fases · {project.solution_type}</div></div>)}</div>}</section>
 </main>
}
