"use client";
import{useEffect,useMemo,useState}from"react";
import Link from"next/link";
import{ArrowLeft,Save,Target,Users}from"lucide-react";
import{supabase}from"@/lib/supabase";

type Unit={id:string;name:string;rank:number;territorial_priority:string|null;ipe_territorial:number|null;hsi:number|null;territorial_confidence:string|null};
type Project={id:string;name:string;objective:string|null;solution_type:string;status:string;school_count:number;phase_count:number;estimated_cost:number|null;baseline:unknown;targets:unknown};
const p=(x:string|null|undefined)=>x?.startsWith("P1")?"P1":x?.startsWith("P2")?"P2":x?.startsWith("P3")?"P3":"P4";
export default function Projeto(){
 const[units,setUnits]=useState<Unit[]>([]),[selected,setSelected]=useState<string[]>([]),[projects,setProjects]=useState<Project[]>([]),[name,setName]=useState("Projeto Piloto SIGES — Segurança Escolar"),[objective,setObjective]=useState("Validar um modelo integrado de diagnóstico, intervenção e mensuração da segurança no entorno escolar."),[solution,setSolution]=useState("ALUNO_GUIA"),[months,setMonths]=useState(4),[cost,setCost]=useState(""),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const[u,r]=await Promise.all([supabase().from("units").select("id,name,rank,territorial_priority,ipe_territorial,hsi,territorial_confidence").order("ipe_territorial",{ascending:false}),supabase().from("strategy_projects").select("*").order("created_at",{ascending:false})]);setUnits((u.data as Unit[])||[]);setProjects((r.data as Project[])||[])};
 useEffect(()=>{load()},[]);
 const priority=useMemo(()=>units.filter(x=>["P1","P2"].includes(p(x.territorial_priority))),[units]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const selectP1=()=>setSelected(units.filter(x=>p(x.territorial_priority)==="P1").map(x=>x.id));
 const selectP12=()=>setSelected(priority.map(x=>x.id));
 const baseline=useMemo(()=>{const s=units.filter(x=>selected.includes(x.id));const avg=(k:keyof Unit)=>s.length?Number((s.reduce((a,x)=>a+Number(x[k]??0),0)/s.length).toFixed(2)):null;return{schools:s.length,p1:s.filter(x=>p(x.territorial_priority)==="P1").length,p2:s.filter(x=>p(x.territorial_priority)==="P2").length,avg_hsi:avg("hsi"),avg_ipe_territorial:avg("ipe_territorial"),average_confidence:avg("territorial_confidence"),measurement_stage:"T0_BASELINE"}},[units,selected]);
 const save=async()=>{if(!name.trim()||!selected.length){setMessage("Informe o nome e selecione pelo menos uma escola.");return}setSaving(true);setMessage("");const phaseCount=Math.max(3,months);const payload={name:name.trim(),objective,solution_type:solution,status:"DRAFT",school_count:selected.length,phase_count:phaseCount,estimated_cost:cost?Number(cost):null,baseline,targets:{measurement_stage:"T2_POS_INTERVENCAO",target_ipe_improvement:null,target_hsi_improvement:null,notes:"Metas quantitativas devem ser definidas após validação do baseline; não são preenchidas automaticamente."},deliverables:["Diagnóstico territorial","Plano de intervenção","Registro de execução","Reavaliação T1/T2"],assumptions:["Validação de campo","Disponibilidade institucional"],risks:["Dados incompletos","Mudança de contexto territorial"]};const{data,error}=await supabase().from("strategy_projects").insert(payload).select().single();if(error){setMessage(`Erro ao salvar: ${error.message}`);setSaving(false);return}if(!data?.id){setMessage("Erro ao salvar: o projeto não retornou um identificador.");setSaving(false);return}const projectId=data.id as string;const links=selected.map(unit_id=>({project_id:projectId,unit_id,role:p(units.find(x=>x.id===unit_id)?.territorial_priority)==="P1"?"PRIORIDADE_CRITICA":"PRIORIDADE_ALTA"}));const{error:linkError}=await supabase().from("strategy_project_units").insert(links);if(linkError){setMessage(`Projeto criado, mas houve erro ao vincular escolas: ${linkError.message}`);setSaving(false);load();return}setMessage("Projeto criado com sucesso.");setSaving(false);load()};
 return <main className="min-h-screen p-4 md:p-8 max-w-[1500px] mx-auto"><Link href="/estrategia" className="muted text-sm flex gap-2 items-center mb-4"><ArrowLeft size={15}/> Centro Estratégico</Link><header className="mb-6"><div className="text-cyan-300 text-xs font-bold tracking-[.22em]">SIGES 3.5 • PROJETO</div><h1 className="text-3xl md:text-5xl font-black mt-1">Simulador de Projeto</h1><p className="muted mt-2 max-w-4xl">Transforme escolas prioritárias em um projeto técnico persistente. O sistema registra a seleção, o baseline e as metas como objetos de projeto; não inventa resultados.</p></header>
 <section className="grid lg:grid-cols-[1.1fr_.9fr] gap-5"><div className="card p-5"><div className="flex items-center gap-2 font-bold mb-4"><Target size={18} className="text-cyan-300"/> 1. Definição</div><label className="muted text-xs">NOME</label><input value={name} onChange={e=>setName(e.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"/><label className="muted text-xs">OBJETIVO</label><textarea value={objective} onChange={e=>setObjective(e.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3 min-h-24"/><label className="muted text-xs">SOLUÇÃO PRINCIPAL</label><select value={solution} onChange={e=>setSolution(e.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"><option value="ALUNO_GUIA">Aluno Guia</option><option value="ENAT_NEUROEDUCACAO">ENAT — Neuroeducação</option><option value="MENSURACAO_SIGES">Mensuração SIGES</option><option value="PLANO_CIRCULACAO">Plano de Circulação Escolar</option><option value="MONITORAMENTO">Monitoramento</option></select><div className="grid grid-cols-2 gap-3"><div><label className="muted text-xs">DURAÇÃO (MESES)</label><input type="number" min="1" max="24" value={months} onChange={e=>setMonths(Number(e.target.value))} className="w-full mt-1 bg-[#07111f] rounded-xl p-3"/></div><div><label className="muted text-xs">CUSTO ESTIMADO (OPCIONAL)</label><input value={cost} onChange={e=>setCost(e.target.value)} placeholder="R$" className="w-full mt-1 bg-[#07111f] rounded-xl p-3"/></div></div></div>
 <aside className="card p-5"><div className="flex items-center gap-2 font-bold mb-4"><Users size={18} className="text-cyan-300"/> 2. Selecionar escolas</div><div className="flex gap-2 mb-4"><button onClick={selectP1} className="px-3 py-2 rounded-xl bg-[#102337] text-sm">Selecionar P1</button><button onClick={selectP12} className="px-3 py-2 rounded-xl bg-[#102337] text-sm">Selecionar P1+P2</button><button onClick={()=>setSelected([])} className="px-3 py-2 rounded-xl bg-[#07111f] text-sm">Limpar</button></div><div className="max-h-[430px] overflow-auto space-y-2">{priority.map(u=><button key={u.id} onClick={()=>toggle(u.id)} className={`w-full text-left rounded-xl p-3 border ${selected.includes(u.id)?"border-cyan-400 bg-cyan-950/20":"border-[#20354a] bg-[#07111f]"}`}><div className="flex justify-between gap-2"><span className="font-semibold">{u.name}</span><span className="text-xs font-bold">{p(u.territorial_priority)}</span></div><div className="muted text-xs mt-1">IPE {u.ipe_territorial??"—"} · HSI {u.hsi??"—"}</div></button>)}</div><div className="mt-4 font-bold">{selected.length} escola(s) selecionada(s)</div></aside></section>
 <section className="grid md:grid-cols-3 gap-4 mt-5"><div className="card p-5"><div className="muted text-xs">T0 • BASELINE</div><div className="text-3xl font-black mt-1">{baseline.schools}</div><div className="muted text-sm">escolas</div><div className="mt-3 text-sm">P1: <b>{baseline.p1}</b> · P2: <b>{baseline.p2}</b><br/>HSI médio: <b>{baseline.avg_hsi??"—"}</b><br/>IPE territorial médio: <b>{baseline.avg_ipe_territorial??"—"}</b></div></div><div className="card p-5"><div className="muted text-xs">FASES</div><div className="text-3xl font-black mt-1">{Math.max(3,months)}</div><div className="muted text-sm">fases sugeridas</div><div className="mt-3 text-sm">1. Diagnóstico<br/>2. Preparação<br/>3. Intervenção<br/>4. T1/T2 conforme duração</div></div><div className="card p-5"><div className="muted text-xs">META</div><div className="text-lg font-bold mt-1">Definição após T0</div><div className="muted text-sm mt-2">O SIGES não cria metas de melhoria sem baseline validado. Elas serão registradas no projeto.</div></div></section>
 <div className="flex justify-end mt-5"><button onClick={save} disabled={saving} className="px-5 py-3 rounded-xl bg-cyan-800 hover:bg-cyan-700 font-bold flex gap-2 items-center disabled:opacity-50"><Save size={17}/>{saving?"Salvando...":"Criar projeto"}</button></div>{message&&<div className="card p-4 mt-4">{message}</div>}
 <section className="mt-8"><h2 className="text-2xl font-black mb-3">Projetos registrados</h2>{projects.length===0?<div className="card p-5 muted">Nenhum projeto criado.</div>:<div className="grid md:grid-cols-2 gap-3">{projects.map(x=><div className="card p-4" key={x.id}><div className="flex justify-between"><b>{x.name}</b><span className="text-xs">{x.status}</span></div><div className="muted text-sm mt-2">{x.school_count} escolas · {x.phase_count} fases · {x.solution_type}</div></div>)}</div>}</section>
 </main>
}