const DETRANS_URL='https://www.joinville.sc.gov.br/publicacoes/estudos-tecnicos-equipamentos-de-fiscalizacao-eletronica-radares-e-lombadas/';
const SCHOOLS='https://geo.joinville.sc.gov.br/server/rest/services/SEPUR/educacao_simgeo_v4/MapServer/1';
const ROADS='https://geo.joinville.sc.gov.br/server/rest/services/SEFAZ/logradouros_sefaz/FeatureServer/0';
const TTL=6*60*60*1000; let cache={data:null,expiresAt:0};
const clean=v=>String(v||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(rua|r|av|av\.|avenida|rodovia|br[- ]?)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const nums=v=>[...String(v||'').matchAll(/(?:n[º°]?\s*)?(\d{2,6})/gi)].map(x=>Number(x[1])).filter(n=>n>0&&n<100000);
async function json(u){const r=await fetch(u,{headers:{'User-Agent':'SIGES-Escola-Segura/3.6 spatial-reader'}});if(!r.ok)throw Error(`Fonte respondeu HTTP ${r.status}`);return r.json()}
async function text(u){const r=await fetch(u,{headers:{'User-Agent':'SIGES-Escola-Segura/3.6 spatial-reader'}});if(!r.ok)throw Error(`DETRANS respondeu HTTP ${r.status}`);return r.text()}
async function schools(){const u=new URL(`${SCHOOLS}/query`);u.searchParams.set('where','1=1');u.searchParams.set('outFields','objectid,escola,endereço,categoria');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','31982');u.searchParams.set('f','json');return (await json(u.toString())).features||[]}
async function roadField(){const j=await json(`${ROADS}?f=json`);return (j.fields||[]).find(f=>/nome.*log|nomelog/i.test(f.name)||/nome.*log/i.test(f.alias||''))?.name||'nomelog'}
async function roadGeometries(road,field){const u=new URL(`${ROADS}/query`);u.searchParams.set('where',`UPPER(${field}) LIKE '%${road.toUpperCase().replace(/'/g,"''")}%'`);u.searchParams.set('outFields','*');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','31982');u.searchParams.set('f','json');return (await json(u.toString())).features||[]}
function distPointLine(p,paths){let best=Infinity;for(const path of paths||[])for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],dx=b[0]-a[0],dy=b[1]-a[1],d=dx*dx+dy*dy,t=d?Math.max(0,Math.min(1,((p.x-a[0])*dx+(p.y-a[1])*dy)/d)):0;best=Math.min(best,Math.hypot(p.x-(a[0]+t*dx),p.y-(a[1]+t*dy)))}return best}
function extractRoad(title){const s=clean(title.replace(/^Estudo Técnico(?: Redutor de Velocidade 40 kmh| Controlador de Velocidade 60km\/h| Controlador de Velocidade Semafórico)?\s*/i,''));return clean((s.match(/(?:Rua|Av\.?|Avenida|Rodovia|BR-)[^,–]+/i)||[])[0]||'')}
function parseDocs(html){const docs=[],re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const title=clean(m[2]);if(!/Estudo Técnico/i.test(title))continue;docs.push({title,url:new URL(m[1],DETRANS_URL).href,road:extractRoad(title),numbers:nums(title)})}return docs}
async function loadDocs(){return parseDocs(await text(DETRANS_URL))}
function exact(s,d){const sa=norm(s.attributes?.['endereço']);const dr=norm(d.road);const an=nums(s.attributes?.['endereço']);return dr&&sa.includes(dr)&&an.some(n=>d.numbers.includes(n))}
function corridor(s,d){return norm(s.attributes?.['endereço']).includes(norm(d.road))}
async function build(){if(cache.data&&cache.expiresAt>Date.now())return cache.data;const [sf,docs,field]=await Promise.all([schools(),loadDocs(),roadField()]);const roads=new Map(),rows=[];for(const s of sf){const p=s.geometry;let best={class:'sem correspondência',confidence:0,distanceMeters:null,study:null};for(const d of docs){if(exact(s,d)){best={class:'DETRANS — ponto exato',confidence:100,distanceMeters:0,study:d};break}if(corridor(s,d)&&best.confidence<75)best={class:'DETRANS — mesmo corredor',confidence:75,distanceMeters:null,study:d};if(!corridor(s,d)){const key=norm(d.road);if(!key)continue;if(!roads.has(key))roads.set(key,await roadGeometries(d.road,field));for(const g of roads.get(key)){const dm=distPointLine(p,g.geometry?.paths||[]);if(dm<=250&&best.confidence<65)best={class:'DETRANS — proximidade espacial',confidence:65,distanceMeters:Math.round(dm),study:d}}}}rows.push({schoolId:s.attributes?.objectid,school:s.attributes?.escola,address:s.attributes?.['endereço'],correspondence:best.class,confidence:best.confidence,distanceMeters:best.distanceMeters,studyTitle:best.study?.title||null,studyUrl:best.study?.url||null})}const summary=rows.reduce((a,r)=>(a[r.correspondence]=(a[r.correspondence]||0)+1,a),{});const data={source:'DETRANS+SIMGEO',retrievedAt:new Date().toISOString(),thresholdMeters:250,summary,records:rows,methodology:{exact:'mesmo logradouro normalizado + número do endereço escolar presente no título do estudo',corridor:'mesmo logradouro normalizado, sem afirmar proximidade métrica do equipamento',spatial:'ponto escolar SIMGeo até 250 m da geometria do corredor estudado; não significa que o equipamento esteja a 250 m da escola',none:'nenhum critério atendido'}};cache={data,expiresAt:Date.now()+TTL};return data}
module.exports=build;