"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Map,School,ShieldAlert,ClipboardCheck,Search,RefreshCw,UserRound} from "lucide-react";
import {supabase} from "@/lib/supabase";
type Unit={id:string;name:string;unit_type:string;neighborhood:string;address:string;rank:number;hsi:number;ipe:number;priority:string;confidence_score:number;technical_evidence_score:number;data_status:string};
export default function Home(){
 const [units,setUnits]=useState<Unit[]>([]); const [q,setQ]=useState(""); const [priority,setPriority]=useState("TODAS"); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);const {data}=await supabase().from("units").select("*").order("rank",{ascending:true});setUnits(data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>units.filter(u=>(priority==="TODAS"||u.priority?.startsWith(priority))&&(`${u.name} ${u.neighborhood} ${u.address}`.toLowerCase().includes(q.toLowerCase()))),[units,q,priority]);
 const p1=units.filter(u=>u.priority?.startsWith("P1")).length,p2=units.filter(u=>u.priority?.startsWith("P2")).length,tech=units.filter(u=>Number(u.technical_evidence_score)>=100).length;
 return <main className="min-h-screen p-4 md:p-8 max-w-[1600px] mx-auto">
  <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-7"><div><div className="text-cyan-300 text-sm font-bold tracking-widest">ENAT • HSI • SIGES</div><h1 className="text-3xl md:text-4xl font-black mt-1">SIGES — Escola Segura</h1><p className="muted mt-1">Gestão territorial baseada no HSI-DOTH-P Escolar 3.1</p></div><div className="flex gap-2"><Link href="/aluno-guia" className="card px-4 py-3 flex gap-2 items-center justify-center hover:bg-[#102337]"><UserRound size={17}/> Aluno Guia</Link><button onClick={load} className="card px-4 py-3 flex gap-2 items-center justify-center"><RefreshCw size={17}/> Atualizar</button></div></header>
  <section className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">{[[units.length,"Unidades",School],[p1,"P1 críticas",ShieldAlert],[p2,"P2 altas",ShieldAlert],[tech,"Evidência técnica",ClipboardCheck]].map(([v,l,I]:any)=><div className="card p-4" key={l}><I size={18} className="text-cyan-300"/><div className="text-2xl font-black mt-2">{v}</div><div className="muted text-sm">{l}</div></div>)}</section>
  <section className="card p-4 mb-5"><div className="flex flex-col lg:flex-row gap-3"><div className="flex-1 flex items-center gap-2 bg-[#07111f] rounded-xl px-3"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar unidade, bairro ou endereço..." className="bg-transparent outline-none w-full py-3"/></div><select value={priority} onChange={e=>setPriority(e.target.value)} className="bg-[#07111f] rounded-xl px-3 py-3"><option>TODAS</option><option>P1</option><option>P2</option><option>P3</option><option>P4</option></select></div></section>
  <section className="grid lg:grid-cols-[1.4fr_.6fr] gap-5"><div className="card overflow-hidden"><div className="p-4 border-b border-[#1f3347] flex justify-between"><div><h2 className="font-bold">Matriz Escolar</h2><p className="muted text-xs mt-1">HSI + IPE + evidência + confiabilidade</p></div><span className="pill p3">{filtered.length} registros</span></div><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left muted border-b border-[#1f3347]"><th className="p-3">#</th><th className="p-3">Unidade</th><th className="p-3">Bairro</th><th className="p-3">HSI</th><th className="p-3">IPE</th><th className="p-3">Prioridade</th></tr></thead><tbody>{loading?<tr><td className="p-5" colSpan={6}>Carregando...</td></tr>:filtered.map(u=><tr key={u.id} className="border-b border-[#132638] hover:bg-[#102337]"><td className="p-3">{u.rank}</td><td className="p-3 font-semibold">{u.name}<div className="muted text-xs">{u.unit_type}</div></td><td className="p-3">{u.neighborhood}</td><td className="p-3 font-bold">{u.hsi}</td><td className="p-3 font-bold">{u.ipe}</td><td className="p-3"><span className={"pill "+(u.priority?.startsWith("P1")?"p1":u.priority?.startsWith("P2")?"p2":u.priority?.startsWith("P3")?"p3":"p4")}>{u.priority}</span></td></tr>)}</tbody></table></div></div>
  <div className="space-y-5"><div className="card p-5 min-h-[260px]"><div className="flex items-center gap-2 font-bold"><Map size={18} className="text-cyan-300"/> Mapa territorial</div><div className="mt-4 h-48 rounded-xl bg-[#091624] border border-dashed border-[#29445c] flex items-center justify-center text-center muted text-sm p-5">Camada geográfica preparada para coordenadas, estudos DETRANS, corredores e raio de influência.</div></div><div className="card p-5"><h3 className="font-bold mb-3">Camadas SIGES</h3><ul className="space-y-2 muted text-sm"><li>• Aluno Guia — análise individual HSI-DOTH-P</li><li>• Vistorias de campo</li><li>• Evidências oficiais e fontes</li><li>• Plano de intervenção</li><li>• Auditoria e governança</li></ul></div></div></section>
 </main>
}
