import DATA_B64 from '../data/joinville-3-2-data.gz.b64?raw';
import{buildEvidenceTrace,formatEvidenceTrace}from'./evidenceTrace';
const clean=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(rua|r|av|av\.|avenida|rodovia|br[- ]?)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const nonEmptyRow=x=>x&&Object.values(x).some(v=>String(v??'').trim()!=='');
const validMatrixRow=x=>nonEmptyRow(x)&&String(x.Unidade??'').trim()!=='';
const validEvidenceRow=x=>nonEmptyRow(x);
const validCrashRow=x=>nonEmptyRow(x)&&(String(x.Via??x.Corredor??'').trim()!=='');
const api=async path=>{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()};
async function loadStatic(){const b=atob(String(DATA_B64).replace(/\s+/g,''));const bytes=Uint8Array.from(b,c=>c.charCodeAt(0));if(typeof DecompressionStream==='undefined')throw new Error('Este navegador não suporta descompressão gzip.');const ds=new DecompressionStream('gzip');const json=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).json();return{matrix:(json['MATRIZ 3.2']||[]).filter(validMatrixRow),evidencias:(json['EVIDÊNCIAS TERRITORIAIS']||[]).filter(validEvidenceRow),sinistros:(json['SINISTROS_CORREDORES']||[]).filter(validCrashRow),dashboard:json['DASHBOARD 3.2']||[],metodologia:json['METODOLOGIA 3.2']||[],dicionario:json['DICIONÁRIO 3.2']||[]}}
const isMissing=v=>v==null||String(v).trim()===''||String(v).trim()==='—'||String(v).trim()==='-';
const firstDefined=(...values)=>values.find(v=>!isMissing(v));
const priorityCode=v=>String(v??'').match(/\bP[1-4]\b/)?.[0]||'';
function resolveTerritorialPriority(row){const matrix=priorityCode(row.Prioridade);const raw=priorityCode(row['Prioridade Territorial 3.2']);const confidence=Number(row['Confiabilidade territorial']);const availability=String(row['Dados territoriais disponíveis']??'').trim();const hasTerritorialMatch=availability!==''&&availability.toLowerCase()!=='sem correspondência';if(raw&&Number.isFinite(confidence)&&confidence>=60&&hasTerritorialMatch)return{value:raw,validated:true,reason:'Prioridade territorial mantida porque há correspondência territorial identificada e confiabilidade suficiente.'};if(matrix)return{value:matrix,validated:false,reason:'Prioridade territorial não validada: evidência territorial insuficiente ou sem correspondência; foi preservada a prioridade da matriz para evitar elevação indevida.'};return{value:raw||'—',validated:false,reason:'Prioridade territorial sem validação suficiente; não foi possível estabelecer correspondência territorial confiável.'}}
function enrich(base,sources){const cb=sources.cbvj?.corridors||[],det=sources.detrans?.corridors||[],docs=sources.detrans?.documents||[],cycles=sources.simgeo?.corridors||[];const match=(a,b)=>{a=clean(a);b=clean(b);return a&&b&&(a.includes(b)||b.includes(a))};const matchedCycle=(key)=>cycles.filter(r=>match(key,r.nome_logra));const matchedDetransDoc=(key)=>docs.find(r=>match(key,r.road)&&Number.isFinite(Number(r.speedKmh)));const matrix=base.matrix.map(x=>{const key=x['Corredor normalizado']||x.Corredor||x.Via||x.Endereço||'';const c=cb.find(r=>match(key,r.road)||match(key,r.road2025||r.road));const d=det.find(r=>match(key,r.road));const doc=matchedDetransDoc(key);const cyc=matchedCycle(key);const next={...x};const accident2025=firstDefined(c?.value2025,x['Acidentes corredor 2025']);const variation=firstDefined(c?.variation2024to2025,x['Variação acidentes 2024-2025']);const studies=firstDefined(d?.count,x['Estudos DETRANS']);const studyYear=firstDefined(doc?.year,x['Ano estudo DETRANS']);if(!isMissing(accident2025))next['Acidentes corredor 2025']=accident2025;if(!isMissing(variation))next['Variação acidentes 2024-2025']=variation;if(!isMissing(studies))next['Estudos DETRANS']=studies;if(!isMissing(studyYear))next['Ano estudo DETRANS']=studyYear;if(isMissing(x['Velocidade km/h'])&&isMissing(x.Velocidade)&&doc?.speedKmh)next['Velocidade km/h']=doc.speedKmh;if(isMissing(x.Velocidade)&&doc?.speedKmh)next.Velocidade=doc.speedKmh;if(isMissing(x['Infraestrutura cicloviária'])&&cyc.length)next['Infraestrutura cicloviária']={valor:'Presente',segmentos:cyc.length,fonte:'SIMGEO'};return next});const sinistros=base.sinistros.map(x=>{const c=cb.find(r=>match(x.Via||x.Corredor||'',r.road)||match(x.Via||x.Corredor||'',r.road2025||r.road));const next={...x};const accident2025=firstDefined(c?.value2025,x['Acidentes 2025']);const variation=firstDefined(c?.variation2024to2025,x['Variação 2024-2025']);if(!isMissing(accident2025))next['Acidentes 2025']=accident2025;if(!isMissing(variation))next['Variação 2024-2025']=variation;return next});return{...base,matrix,sinistros,sources,meta:{updatedAt:sources.generatedAt||new Date().toISOString(),latestYear:Math.max(2025,...Object.values(sources).map(s=>Number(s?.latestCompleteYear)||0)),liveSources:Object.values(sources).filter(Boolean).length}}}
function completeness(row){const fields=[['Velocidade km/h','Velocidade'],['VDM','VDM'],['Sinistros 3 anos','Sinistros 3 anos'],['Travessias','Travessias'],['Calçada','Calçada'],['Sinalização','Sinalização'],['Iluminação','Iluminação'],['Embarque/Desembarque','Embarque/Desembarque'],['Infraestrutura cicloviária','Infraestrutura cicloviária']];const available=fields.filter(([,b])=>!isMissing(row[b])||!isMissing(row[`${b} oficial`])).length;return{available,total:fields.length,percent:Math.round((available/fields.length)*100),missing:fields.filter(([,b])=>isMissing(row[b])&&isMissing(row[`${b} oficial`])).map(([a])=>a)}}
export function classifySchool(row){const c=completeness(row);if(c.available<=6)return{status:'NECESSITA DE DADOS COMPLEMENTARES',code:'COMPLEMENTARES',percent:c.percent,available:c.available,total:c.total,missing:c.missing,recommendation:'Complementar os dados territoriais inexistentes no relatório antes da decisão institucional sobre a adoção de Aluno Guia.'};return{status:'DECISÃO INSTITUCIONAL SOBRE ALUNO GUIA',code:'DECISAO_INSTITUCIONAL',percent:c.percent,available:c.available,total:c.total,missing:c.missing,recommendation:'A escola dispõe de evidências territoriais suficientes para decisão institucional. A adoção de Aluno Guia é facultativa e deve ser definida pela instituição, considerando seu contexto e avaliação de risco.'}}
export async function loadSigesData(){const base=await loadStatic();let sources={};try{const snapshot=await api(`${import.meta.env.BASE_URL}public-sources.json`);sources=snapshot}catch{const results=await Promise.allSettled(['/api/public-sources/cbvj','/api/public-sources/detrans','/api/public-sources/simgeo'].map(api));results.forEach((r,i)=>{if(r.status==='fulfilled')sources[['cbvj','detrans','simgeo'][i]]=r.value})}const data=enrich(base,sources);data.matrix=data.matrix.map(x=>{const territorial=resolveTerritorialPriority(x);const d=classifySchool(x);const raw=priorityCode(x['Prioridade Territorial 3.2']);const priorityFields=raw&&raw!==territorial.value?{'Prioridade Territorial 3.2 original':raw}:{};return{...x,...priorityFields,'Prioridade Territorial 3.2':territorial.value,'Status da prioridade territorial SIGES':territorial.validated?'VALIDADA':'NÃO VALIDADA','Justificativa da prioridade territorial SIGES':territorial.reason,'Classificação SIGES':d.status,'Cobertura de evidências SIGES':`${d.available}/${d.total} (${d.percent}%)`,'Dados disponíveis SIGES':d.available,'Dados ausentes SIGES':d.missing.length?d.missing.join(', '):'Nenhum campo crítico ausente','Providência recomendada SIGES':d.recommendation,'Rastreabilidade SIGES':formatEvidenceTrace(buildEvidenceTrace(x,data.sources))||'Nenhuma evidência pública adicional correspondente foi identificada para esta unidade.'}});return data}
