import DATA_B64 from '../data/joinville-3-2-data.gz.b64?raw';
const clean=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(rua|r|av|av\.|avenida|rodovia|br[- ]?)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const nonEmptyRow=x=>x&&Object.values(x).some(v=>String(v??'').trim()!=='');
const validMatrixRow=x=>nonEmptyRow(x)&&String(x.Unidade??'').trim()!=='';
const validEvidenceRow=x=>nonEmptyRow(x);
const validCrashRow=x=>nonEmptyRow(x)&&(String(x.Via??x.Corredor??'').trim()!=='');
const api=async path=>{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()};
async function loadStatic(){const b=atob(String(DATA_B64).replace(/\s+/g,''));const bytes=Uint8Array.from(b,c=>c.charCodeAt(0));if(typeof DecompressionStream==='undefined')throw new Error('Este navegador não suporta descompressão gzip.');const ds=new DecompressionStream('gzip');const json=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).json();return{matrix:(json['MATRIZ 3.2']||[]).filter(validMatrixRow),evidencias:(json['EVIDÊNCIAS TERRITORIAIS']||[]).filter(validEvidenceRow),sinistros:(json['SINISTROS_CORREDORES']||[]).filter(validCrashRow),dashboard:json['DASHBOARD 3.2']||[],metodologia:json['METODOLOGIA 3.2']||[],dicionario:json['DICIONÁRIO 3.2']||[]}}
const isMissing=v=>v==null||String(v).trim()===''||String(v).trim()==='—'||String(v).trim()==='-';
const firstDefined=(...values)=>values.find(v=>!isMissing(v));
function enrich(base,sources){const cb=sources.cbvj?.corridors||[],det=sources.detrans?.corridors||[],docs=sources.detrans?.documents||[],cycles=sources.simgeo?.corridors||[];const match=(a,b)=>{a=clean(a);b=clean(b);return a&&b&&(a.includes(b)||b.includes(a))};const matchedCycle=(key)=>cycles.filter(r=>match(key,r.nome_logra));const matchedDetransDoc=(key)=>docs.find(r=>match(key,r.road)&&Number.isFinite(Number(r.speedKmh)));const matrix=base.matrix.map(x=>{const key=x['Corredor normalizado']||x.Corredor||x.Via||x.Endereço||'';const c=cb.find(r=>match(key,r.road)||match(key,r.road2025||r.road));const d=det.find(r=>match(key,r.road));const doc=matchedDetransDoc(key);const cyc=matchedCycle(key);const next={...x};const accident2025=firstDefined(c?.value2025,x['Acidentes corredor 2025']);const variation=firstDefined(c?.variation2024to2025,x['Variação acidentes 2024-2025']);const studies=firstDefined(d?.count,x['Estudos DETRANS']);const studyYear=firstDefined(doc?.year,x['Ano estudo DETRANS']);if(!isMissing(accident2025))next['Acidentes corredor 2025']=accident2025;if(!isMissing(variation))next['Variação acidentes 2024-2025']=variation;if(!isMissing(studies))next['Estudos DETRANS']=studies;if(!isMissing(studyYear))next['Ano estudo DETRANS']=studyYear;if(isMissing(x['Velocidade km/h'])&&isMissing(x.Velocidade)&&doc?.speedKmh)next['Velocidade km/h']=doc.speedKmh;if(isMissing(x.Velocidade)&&doc?.speedKmh)next.Velocidade=doc.speedKmh;if(isMissing(x['Infraestrutura cicloviária'])&&cyc.length)next['Infraestrutura cicloviária']={valor:'Presente',segmentos:cyc.length,fonte:'SIMGEO'};return next});const sinistros=base.sinistros.map(x=>{const c=cb.find(r=>match(x.Via||x.Corredor||'',r.road)||match(x.Via||x.Corredor||'',r.road2025||r.road));const next={...x};const accident2025=firstDefined(c?.value2025,x['Acidentes 2025']);const variation=firstDefined(c?.variation2024to2025,x['Variação 2024-2025']);if(!isMissing(accident2025))next['Acidentes 2025']=accident2025;if(!isMissing(variation))next['Variação 2024-2025']=variation;return next});return{...base,matrix,sinistros,sources,meta:{updatedAt:sources.generatedAt||new Date().toISOString(),latestYear:Math.max(2025,...Object.values(sources).map(s=>Number(s?.latestCompleteYear)||0)),liveSources:Object.values(sources).filter(Boolean).length}}}
export async function loadSigesData(){const base=await loadStatic();let sources={};try{const snapshot=await api(`${import.meta.env.BASE_URL}public-sources.json`);sources=snapshot}catch{const results=await Promise.allSettled(['/api/public-sources/cbvj','/api/public-sources/detrans','/api/public-sources/simgeo'].map(api));results.forEach((r,i)=>{if(r.status==='fulfilled')sources[['cbvj','detrans','simgeo'][i]]=r.value})}return enrich(base,sources)}
