import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./hsi-bullying-operacional.css';

const dims=[
 ['seguranca_percebida','Percepção de segurança'],['pertencimento','Pertencimento'],['respeito','Respeito e convivência'],['pressao_dos_pares','Pressão dos pares'],['confianca_para_pedir_ajuda','Confiança para pedir ajuda'],['resposta_escolar','Resposta escolar']
];
const weights={seguranca_percebida:.20,pertencimento:.15,respeito:.20,pressao_dos_pares:.15,confianca_para_pedir_ajuda:.15,resposta_escolar:.15};
const qs=[
['B01','seguranca_percebida','Na escola, sinto que posso participar das atividades sem medo de ser humilhado ou intimidado.'],['B02','seguranca_percebida','Se ocorrer uma situação de bullying, sinto que haverá adultos preparados para ajudar.'],['B03','seguranca_percebida','Consigo circular pelos espaços da escola sem evitar lugares por medo de colegas.'],['B04','seguranca_percebida','Sinto-me seguro durante recreios, intervalos e momentos de maior circulação.'],['B05','seguranca_percebida','Sinto que a escola leva a sério situações repetidas de intimidação.'],
['B06','pertencimento','Sinto que faço parte da comunidade escolar.'],['B07','pertencimento','Tenho colegas com quem posso contar quando preciso.'],['B08','pertencimento','Sinto que posso ser eu mesmo sem ser ridicularizado.'],['B09','pertencimento','Percebo que as diferenças entre os estudantes são respeitadas.'],['B10','pertencimento','Quando alguém fica isolado, percebo oportunidades para incluir essa pessoa.'],
['B11','respeito','Os estudantes costumam tratar uns aos outros com respeito.'],['B12','respeito','Brincadeiras que machucam, humilham ou expõem alguém são reconhecidas como um problema.'],['B13','respeito','Apelidos ofensivos não são tratados como algo normal na minha escola.'],['B14','respeito','Comentários sobre aparência, origem, deficiência ou outras características são tratados com responsabilidade.'],['B15','respeito','Quando presencio uma agressão ou humilhação, sei que devo buscar ajuda.'],
['B16','pressao_dos_pares','Às vezes estudantes participam de provocações para serem aceitos pelo grupo.'],['B17','pressao_dos_pares','Existe pressão para rir, compartilhar ou incentivar situações que humilham alguém.'],['B18','pressao_dos_pares','Tenho dificuldade de contrariar colegas quando o grupo decide intimidar alguém.'],['B19','pressao_dos_pares','Redes sociais podem aumentar a pressão para participar de conflitos entre estudantes.'],['B20','pressao_dos_pares','Sei identificar quando uma brincadeira está sendo usada para pressionar ou excluir alguém.'],
['B21','confianca_para_pedir_ajuda','Se eu sofrer bullying, saberia a quem procurar na escola.'],['B22','confianca_para_pedir_ajuda','Eu me sentiria seguro contando a um adulto sobre uma situação de bullying.'],['B23','confianca_para_pedir_ajuda','Acredito que pedir ajuda não deve gerar retaliação ou mais exposição.'],['B24','confianca_para_pedir_ajuda','Se um colega sofrer bullying, eu saberia como procurar ajuda para ele.'],['B25','confianca_para_pedir_ajuda','A escola oferece caminhos claros para comunicar situações de violência ou intimidação.'],
['B26','resposta_escolar','Quando um caso é comunicado, a escola procura compreender o que aconteceu antes de agir.'],['B27','resposta_escolar','A escola acompanha situações repetidas depois da primeira intervenção.'],['B28','resposta_escolar','As ações de prevenção ao bullying envolvem estudantes, professores e famílias quando necessário.'],['B29','resposta_escolar','Percebo mudanças positivas quando a escola realiza ações de prevenção e convivência.'],['B30','resposta_escolar','Sinto que a escola aprende com os casos registrados e melhora suas ações.']];

function calc(a){const out={};dims.forEach(([k])=>{const v=qs.filter(q=>q[1]===k).map(q=>a[q[0]]);const m=v.reduce((x,y)=>x+y,0)/v.length;out[k]=Math.round(((m-1)/4)*100)});return Math.round(dims.reduce((s,[k])=>s+out[k]*weights[k],0));}
function label(v){return v>=80?'Proteção percebida elevada':v>=60?'Proteção percebida intermediária':v>=40?'Atenção preventiva necessária':'Prioridade preventiva elevada'}
function App(){const[a,setA]=useState({});const[phase,setPhase]=useState('baseline');const[saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('siges_hsi_bullying_history')||'[]'));const[done,setDone]=useState(false);const score=useMemo(()=>Object.keys(a).length===30?calc(a):null,[a]);
 const save=()=>{if(score===null)return;const item={phase,score,at:new Date().toISOString()};const next=[...saved,item].slice(-10);localStorage.setItem('siges_hsi_bullying_history',JSON.stringify(next));setSaved(next);setDone(true)};
 const before=saved.length?saved[saved.length-1].score:null;const delta=score!==null&&before!==null?score-before:null;
 return <div className="page"><header><div><span className="eyebrow">SIGES · CENTRO DE INTELIGÊNCIA</span><h1>HSI-DOTH-P Bullying</h1><p>Da percepção escolar à intervenção preventiva.</p></div><span className="badge">{phase==='baseline'?'BASELINE':'REAVALIAÇÃO'}</span></header>
 <div className="notice"><b>Proteção de dados.</b> Esta avaliação é educacional e preventiva. Não é diagnóstico clínico. Resultados individuais devem ser tratados com acesso restrito e painéis territoriais devem usar dados agregados.</div>
 <section className="steps">{['BASELINE','PERFIL','SINAIS','INTERVENÇÃO','REAVALIAÇÃO','EVOLUÇÃO'].map((x,i)=><div className={(phase==='baseline'&&i===0)||done&&i>0?'step active':'step'} key={x}><small>{i+1}</small>{x}</div>)}</section>
 <main><section className="questions"><div className="section-head"><div><span>30 ITENS</span><h2>Avaliação de convivência e segurança</h2></div><strong>{Object.keys(a).length}/30</strong></div>{dims.map(([key,title])=><div className="dimension" key={key}><h3>{title}</h3>{qs.filter(q=>q[1]===key).map(q=><div className="q" key={q[0]}><p><b>{q[0]}</b> {q[2]}</p><div className="scale">{[1,2,3,4,5].map(v=><button className={a[q[0]]===v?'selected':''} onClick={()=>setA({...a,[q[0]]:v})} key={v}>{v}<small>{['Discordo','Pouco','Neutro','Concordo','Concordo muito'][v-1]}</small></button>)}</div></div>)}</div>)}</section>
 <aside><div className="result"><span>ÍNDICE</span><strong>{score??'—'}</strong><em>{score!==null?label(score):'Complete os 30 itens'}</em>{score!==null&&<div className="bar"><i style={{width:`${score}%`}}/></div>}{delta!==null&&<p>Evolução em relação ao último registro: <b>{delta>0?'+':''}{delta} pontos</b></p>}</div><div className="dimensions"><span>DIMENSÕES</span>{dims.map(([k,t])=>{const vals=qs.filter(q=>q[1]===k).map(q=>a[q[0]]).filter(Boolean);const v=vals.length===5?Math.round(((vals.reduce((x,y)=>x+y,0)/5-1)/4)*100):null;return <div key={k}><label>{t}</label><b>{v??'—'}</b></div>})}</div><button className="primary" disabled={score===null} onClick={save}>{done?'Avaliação registrada':'Registrar resultado'}</button><button className="secondary" onClick={()=>{setPhase('reassessment');setDone(false);setA({})}}>Iniciar reavaliação</button></aside></main></div>}
createRoot(document.getElementById('app')).render(<App/>);
