import React from 'react';
import {ShieldCheck,ArrowRight,HeartHandshake,TrafficCone,Map,Activity,LockKeyhole,BrainCircuit} from 'lucide-react';
import './inteligencia.css';
const cards=[
 {title:'Radar da Escola',text:'Visão operacional dos riscos, prioridades, sinais e próxima melhor ação.',icon:Map,href:'/radar.html',tag:'INTELIGÊNCIA OPERACIONAL'},
 {title:'HSI-DOTH-P Bullying',text:'Ciclo protegido: baseline, perfil, sinais, intervenção, reavaliação e evolução.',icon:HeartHandshake,href:'/hsi-bullying.html',tag:'PRIORIDADE HUMANA'},
 {title:'Segurança no trânsito escolar',text:'Estrutura preparada para correlacionar percepção de risco, território, ocorrências e resultados.',icon:TrafficCone,href:'/radar.html',tag:'SEGURANÇA VIÁRIA'},
];
export default function App(){return <div className="ih"><header><div className="ih-logo"><ShieldCheck/> <b>SIGES</b><small>ESCOLA SEGURA</small></div><span><LockKeyhole size={14}/> arquitetura protegida</span></header><main><section className="ih-hero"><div className="kicker">CENTRO DE INTELIGÊNCIA SIGES</div><h1>Observar. Qualificar. Correlacionar. Agir.</h1><p>Uma camada de inteligência para transformar o cotidiano escolar em evidência útil para prevenção, intervenção e decisão pública — com governança, rastreabilidade e proteção de dados.</p><div className="ih-flow">{['OBSERVAR','QUALIFICAR','CORRELACIONAR','PRIORIZAR','AGIR','VERIFICAR','APRENDER'].map((x,i)=><div key={x}><i>{i+1}</i>{x}</div>)}</div></section><section className="ih-grid">{cards.map(({title,text,icon:Icon,href,tag})=><a className="ih-card" href={href} key={title}><div className="ih-icon"><Icon/></div><small>{tag}</small><h2>{title}</h2><p>{text}</p><strong>Abrir módulo <ArrowRight size={16}/></strong></a>)}</section><section className="ih-principles"><div><BrainCircuit/><b>IA preparada, não soberana</b><p>Futuras IAs poderão interpretar sinais e sugerir caminhos. Não terão permissão para alterar avaliações, aprovar reivindicações, emitir certificados, mudar acessos ou apagar evidências.</p></div><div><Activity/><b>Inteligência explicável</b><p>Cada prioridade deve mostrar os fatores que contribuíram para o sinal, sua confiança e sua versão de regra.</p></div><div><LockKeyhole/><b>Interoperabilidade segura</b><p>A futura integração com a Central ENAT-HSI e outras IAs será feita por contratos de API versionados, sem compartilhamento direto de banco de dados.</p></div></section></main><footer>ENAT · SIGES Escola Segura · Centro de Inteligência · arquitetura preparada para integração futura</footer></div>}
