import React,{useMemo,useState,useEffect}from'react';
import{createRoot}from'react-dom/client';
import{ShieldCheck,LayoutDashboard,School,Map,Activity,TriangleAlert,ClipboardList,Target,FileSearch,UserCheck,BookOpenCheck,FileCheck,ScrollText,Settings2,LockKeyhole,Search,LogOut,ChevronRight,Route,Database}from'lucide-react';
import{loadSigesData}from'./dataLoader';
import'./styles.css';

const nav=[['dashboard','Dashboard',LayoutDashboard],['base','Base Escolar',School],['radar','Radar Territorial',Map],['transito','HSI-DOTH-P Trânsito',Activity],['bullying','HSI-DOTH-P Bullying',TriangleAlert],['evidencias','Evidências',FileSearch],['sinistros','Sinistros / Corredores',Route],['riscos','Riscos e Ocorrências',TriangleAlert],['reivindicacoes','Reivindicações',ClipboardList],['plano','Plano de Ação',Target],['guia','Aluno Guia',UserCheck],['formacao','Formação',BookOpenCheck],['relatorios','Relatórios',FileCheck],['auditoria','Auditoria',ScrollText],['configuracoes','Configurações',Settings2]];
const opKey='siges_ops_v5';
const num=v=>Number(v)||0;
const priority=v=>{const m=String(v||'').match(/P[1-4]/);return m?m[0]:'P4'};
const text=v=>v==null||v===''?'—':String(v);

function Gate(){const[pw,setPw]=useState(''),[err,setErr]=useState('');const enter=()=>{if(pw!=='SIGES2026')return setErr('Senha de acesso incorreta.');sessionStorage.setItem('siges_closed_access','1');location.reload()};return <div className="gate"><div className="gate-card"><div className="brand"><ShieldCheck size={30}/></div><small>ENAT · AMBIENTE CONTROLADO</small><h1>SIGES</h1><h2>ESCOLA SEGURA</h2><p>Base territorial de risco escolar de Joinville · HSI-DOTH-P Escolar 3.2</p><label>Senha de acesso<input autoFocus type="password" value={pw} onChange={e=>{setPw(e.target.value);setErr('')}} onKeyDown={e=>e.key==='Enter'&&enter()}/></label>{err&&<div className="error">{err}</div>}<button className="primary" onClick={enter}><LockKeyhole size={16}/> Entrar no sistema</button><div className="gate-note">Acesso fechado. A fonte territorial é somente leitura.</div></div></div>}

function App(){const[data,setData]=useState(null),[err,setErr]=useState('');useEffect(()=>{loadSigesData().then(setData).catch(e=>setErr(e.message))},[]);if(!sessionStorage.getItem('siges_closed_access'))return <Gate/>;if(err)return <div className="gate"><div className="gate-card"><ShieldCheck size={30}/><h1>Falha na base</h1><p>{err}</p><button className="primary" onClick={()=>location.reload()}>Tentar novamente</button></div></div>;if(!data)return <div className="gate"><div className="gate-card"><Database size={30}/><h1>Carregando SIGES</h1><p>Carregando a base territorial completa 3.2...</p></div></div>;return <Shell data={data}/>}

function Shell({data}){const[page,setPage]=useState('dashboard'),[q,setQ]=useState(''),[ops,setOps]=useState(()=>{try{return JSON.parse(localStorage.getItem(opKey))||{riscos:[],reivindicacoes:[],plano:[],auditoria:[],bullying:[]}}catch{return{riscos:[],reivindicacoes:[],plano:[],auditoria:[],bullying:[]}}});const save=o=>{setOps(o);localStorage.setItem(opKey,JSON.stringify(o))};const lock=()=>{sessionStorage.removeItem('siges_closed_access');location.reload()};const title=nav.find(x=>x[0]===page)?.[1]||'Dashboard';return <div className="app"><aside><div className="side-brand"><div className="mark"><ShieldCheck size={20}/></div><b>SIGES<small>ESCOLA SEGURA</small></b></div><nav>{nav.map(([id,l,I])=><button className={page===id?'active':''} key={id} onClick={()=>{setPage(id);setQ('')}}><I size={17}/>{l}</button>)}</nav><div className="side-foot"><b>ENAT</b><span>Administração</span><button onClick={lock}><LogOut size={14}/> Bloquear</button></div></aside><main><header><span>SIGES / {title}</span><div className="head-right"><div className="search"><Search size={15}/><input placeholder="Pesquisar na base..." value={q} onChange={e=>setQ(e.target.value)}/></div><button onClick={lock}><LockKeyhole size={16}/></button></div></header>{page==='dashboard'?<Dashboard data={data} go={setPage}/>:page==='base'?<Base data={data} q={q}/>:page==='radar'?<Radar data={data}/>:page==='transito'?<Traffic data={data} q={q}/>:page==='bullying'?<Bullying data={data} ops={ops} save={save}/>:page==='evidencias'?<Evidence data={data} q={q}/>:page==='sinistros'?<Crashes data={data}/>:page==='riscos'?<Operational data={data} type="riscos" title="Riscos e Ocorrências" ops={ops} save={save}/>:page==='reivindicacoes'?<Operational data={data} type="reivindicacoes" title="Reivindicações" ops={ops} save={save}/>:page==='plano'?<Operational data={data} type="plano" title="Plano de Ação" ops={ops} save={save}/>:page==='guia'?<Guide data={data}/>:page==='formacao'?<Formation/>:page==='relatorios'?<Reports data={data} ops={ops}/>:page==='auditoria'?<Audit ops={ops}/>:<Settings data={data}/>}</main></div>}

function Dashboard({data,go}){const m=data.matrix,e=data.evidencias,c=data.sinistros;const p1=m.filter(x=>priority(x.Prioridade)==='P1').length,p2=m.filter(x=>priority(x.Prioridade)==='P2').length,p3=m.filter(x=>priority(x.Prioridade)==='P3').length,d=m.filter(x=>String(x['DETRANS no corredor']).toUpperCase()==='SIM').length,a=m.filter(x=>x['Acidentes corredor 2024']!=null).length,hs=Math.round(m.reduce((s,x)=>s+num(x['HSI-DOTH-P']),0)/m.length),ip=Math.round(m.reduce((s,x)=>s+num(x['IPE Territorial 3.2']),0)/m.length);return <section><div className="hero"><div><small>ADMINISTRAÇÃO ENAT · JOINVILLE</small><h1>Do olhar do aluno à decisão pública.</h1><p>O SIGES transforma evidências produzidas pela comunidade escolar em informação qualificada para decisões, intervenções e melhoria contínua da segurança viária.</p></div><button onClick={()=>location.reload()}>Atualizar base</button></div><div className="section-head"><div><small>BASE TERRITORIAL · VERSÃO 3.2</small><h2>Centro de inteligência escolar</h2></div><span>{m.length} unidades · {e.length} evidências · {c.length} corredores</span></div><div className="cards">{[['Unidades na base',m.length,'MATRIZ 3.2'],['P1 territorial',p1,'prioridade crítica'],['P2 territorial',p2,'prioridade muito alta'],['P3 territorial',p3,'prioridade alta'],['HSI médio',hs,'escala 0–100'],['IPE Territorial',ip,'escala 0–100'],['DETRANS no corredor',d,'sinal territorial'],['Acidentes corredor 2024',a,'unidades com registro']].map(x=><div className="metric" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div><div className="grid2"><div className="panel"><small>PRIORIDADE TERRITORIAL</small><h3>Unidades que entram primeiro no radar</h3>{m.filter(x=>priority(x.Prioridade)!=='P4').slice(0,10).map(x=><div className="row" key={x.Rank}><div><b>{x.Unidade}</b><span>{x.Bairro} · IPE {num(x['IPE Territorial 3.2']).toFixed(1)}</span></div><em className={priority(x.Prioridade).toLowerCase()}>{priority(x.Prioridade)}</em></div>)}</div><div className="panel"><small>CICLO DE INTELIGÊNCIA</small><h3>Observar até aprender</h3><div className="cycle">{['OBSERVAR','QUALIFICAR','CORRELACIONAR','PRIORIZAR','AGIR','VERIFICAR','APRENDER'].map(x=><span key={x}>{x}</span>)}</div><p>A matriz 3.2 não transforma ausência de dados em segurança e não substitui levantamento de campo, engenharia de tráfego ou decisão pública.</p><button onClick={()=>go('radar')}>Abrir Radar <ChevronRight size={14}/></button></div></div></section>}

function Base({data,q}){const[f,setF]=useState('TODOS'),[sel,setSel]=useState(null),rows=useMemo(()=>data.matrix.filter(x=>(f==='TODOS'||priority(x.Prioridade)===f)&&(!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()))),[data,q,f]);return <section><div className="section-head"><div><small>FONTE MESTRE · SOMENTE LEITURA</small><h2>Base Escolar</h2><p>Matriz territorial 3.2 preservada para consulta; clique em uma unidade para abrir o dossiê.</p></div><span>{rows.length} registros</span></div><div className="filters">{['TODOS','P1','P2','P3','P4'].map(x=><button className={f===x?'sel':''} onClick={()=>setF(x)} key={x}>{x}</button>)}</div><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Unidade</th><th>Tipo</th><th>Bairro</th><th>HSI</th><th>IPE 3.2</th><th>Prioridade</th><th>DETRANS</th><th>Acidentes 2024</th></tr></thead><tbody>{rows.map(x=><tr key={x.Rank} onClick={()=>setSel(x)}><td>{x.Rank}</td><td><b>{x.Unidade}</b></td><td>{text(x.Tipo)}</td><td>{x.Bairro}</td><td>{num(x['HSI-DOTH-P'])}</td><td>{num(x['IPE Territorial 3.2']).toFixed(1)}</td><td><em className={priority(x.Prioridade).toLowerCase()}>{priority(x.Prioridade)}</em></td><td>{text(x['DETRANS no corredor'])}</td><td>{text(x['Acidentes corredor 2024'])}</td></tr>)}</tbody></table></div>{sel&&<Dossier data={data} x={sel} close={()=>setSel(null)}/>}</section>}

function Dossier({data,x,close}){const relatedE=data.evidencias.filter(e=>String(e['Unidade escolar associada']||'').toLowerCase()===String(x.Unidade||'').toLowerCase()||String(e.Ponto||'').toLowerCase().includes(String(x.Bairro||'').toLowerCase()));const corridor=String(x['Corredor normalizado']||'').toLowerCase();const relatedC=data.sinistros.filter(c=>corridor&&String(c.Via||'').toLowerCase().includes(corridor));const entries=Object.entries(x);return <div className="modal"><div className="modal-card dossier"><button className="close" onClick={close}>×</button><small>DOSSIÊ TERRITORIAL · MATRIZ 3.2</small><h2>{x.Unidade}</h2><p>{text(x.Tipo)} · {text(x.Bairro)} · {text(x.Endereço)}</p><div className="score"><b>{num(x['HSI-DOTH-P'])}</b><span>HSI-DOTH-P</span><b>{num(x['IPE Territorial 3.2']).toFixed(1)}</b><span>IPE TERRITORIAL</span><b>{priority(x['Prioridade'])}</b><span>PRIORIDADE</span></div><div className="dims">{['D','O','T','H','P'].map(k=><div key={k}><b>{k}</b><i><span style={{width:`${Math.min(100,num(x[k]))}%`}}/></i><strong>{text(x[k])}</strong></div>)}</div><h3>Campos da matriz</h3><div className="detail-grid">{entries.filter(([k])=>!['D','O','T','H','P','HSI-DOTH-P','IPE Territorial 3.2'].includes(k)).map(([k,v])=><div key={k}><small>{k}</small><b>{text(v)}</b></div>)}</div><div className="grid2"><div className="panel"><small>EVIDÊNCIAS RELACIONADAS</small><h3>{relatedE.length}</h3>{relatedE.slice(0,8).map((e,i)=><div className="row" key={i}><div><b>{text(e.Tipo)}</b><span>{text(e['Via/Corredor'])} · {text(e.Ponto)}</span></div><em>{text(e['Data/ano'])}</em></div>)}{!relatedE.length&&<p>Nenhuma evidência diretamente associada pelo vínculo disponível.</p>}</div><div className="panel"><small>SINISTROS / CORREDORES</small><h3>{relatedC.length||'—'}</h3>{relatedC.slice(0,8).map((c,i)=><div className="row" key={i}><div><b>{text(c.Via)}</b><span>2023: {text(c['Acidentes 2023'])} · 2024: {text(c['Acidentes 2024'])}</span></div><em>{text(c['Score territorial máximo'])}</em></div>)}{!relatedC.length&&<p>O vínculo será refinado quando a denominação do corredor coincidir.</p>}</div></div><p className="note">A ficha é informativa e rastreável. Não substitui vistoria, validação institucional ou decisão de engenharia.</p></div></div>}

function Radar({data}){const by=useMemo(()=>{const m={};data.matrix.forEach(x=>{const k=x.Bairro||'Não informado';(m[k]??=[]).push(x)});return Object.entries(m).map(([bairro,rows])=>({bairro,n:rows.length,ip:rows.reduce((s,x)=>s+num(x['IPE Territorial 3.2']),0)/rows.length,p1:rows.filter(x=>priority(x.Prioridade)==='P1').length,d:rows.filter(x=>String(x['DETRANS no corredor']).toUpperCase()==='SIM').length})).sort((a,b)=>b.ip-a.ip)},[data]);return <section><div className="section-head"><div><small>INTELIGÊNCIA TERRITORIAL</small><h2>Radar Territorial</h2><p>Leitura agregada por bairro, conectando matriz escolar e sinais territoriais.</p></div><span>{by.length} bairros</span></div><div className="cards">{by.slice(0,6).map(x=><div className="metric" key={x.bairro}><small>{x.bairro}</small><strong>{x.ip.toFixed(1)}</strong><span>{x.n} unidades · {x.p1} P1 · {x.d} DETRANS</span></div>)}</div><div className="panel"><small>HIERARQUIA DE ATENÇÃO</small><h3>Territórios para aprofundamento</h3>{by.map(x=><div className="row" key={x.bairro}><div><b>{x.bairro}</b><span>{x.n} unidades · {x.p1} P1 · {x.d} com DETRANS no corredor</span></div><em>{x.ip.toFixed(1)}</em></div>)}</div></section>}

function Traffic({data,q}){const rows=data.matrix.filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));return <section><div className="section-head"><div><small>HSI-DOTH-P · TRÂNSITO ESCOLAR</small><h2>Dimensões comportamentais</h2><p>Leitura das dimensões D-O-T-H-P e relação com o índice territorial.</p></div><span>{rows.length} unidades</span></div><div className="table-wrap"><table><thead><tr>{['Unidade','Bairro','D','O','T','H','P','HSI-DOTH-P','IPE Territorial 3.2'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.Rank}><td>{x.Unidade}</td><td>{x.Bairro}</td>{['D','O','T','H','P'].map(k=><td key={k}>{text(x[k])}</td>)}<td>{num(x['HSI-DOTH-P'])}</td><td>{num(x['IPE Territorial 3.2']).toFixed(1)}</td></tr>)}</tbody></table></div></section>}

const qs=['Reconheço sinais de bullying ou exclusão.','Sei onde buscar ajuda na escola.','Consigo agir sem seguir pressão dos colegas.','Penso nas consequências antes de responder.','Consigo controlar impulsos diante de provocações.','Respeito diferenças entre colegas.','Sinto pertencimento ao ambiente escolar.','Consigo distinguir brincadeira de humilhação.','Se presencio bullying, sei como agir com segurança.','A escola oferece caminhos claros para relatar situações.','Consigo conversar sem transformar divergência em agressão.','Procuro compreender o efeito das minhas atitudes.','Consigo interromper uma reação impulsiva.','Tenho confiança para pedir ajuda a um adulto.','Percebo influência dos pares no comportamento.','Consigo manter atenção em situações de tensão.','Reorganizo minha atitude depois de um conflito.','Tenho disposição para reparar um dano.','Preservo a privacidade de quem pede ajuda.','Acredito que pedir ajuda é segurança.','Avalio riscos antes de participar de uma situação coletiva.','Tenho estratégias para lidar com pressão social.','Consigo esperar antes de responder a uma provocação.','Sei onde encontrar apoio.','Minhas escolhas podem melhorar a convivência.','Evito compartilhar exposição humilhante.','Reconheço quando alguém está isolado.','Respeito os limites do outro.','Consigo comunicar um problema com clareza.','Estou disposto a contribuir para uma escola mais segura.'];
function Bullying({data,ops,save}){const[a,setA]=useState(Array(30).fill(0)),[school,setSchool]=useState(''),score=Math.round(a.reduce((s,v)=>s+v,0)/150*100);const finish=()=>{if(!school||a.some(v=>!v))return alert('Selecione a unidade e responda todas as 30 questões.');const rec={id:Date.now(),school,score,createdAt:new Date().toISOString()};save({...ops,bullying:[...(ops.bullying||[]),rec]});alert(`HSI-DOTH-P Bullying registrado: ${score}/100`)};return <section><div className="section-head"><div><small>HSI-DOTH-P · BULLYING</small><h2>Avaliação de convivência e segurança humana</h2><p>30 questões · escala Likert 1–5 · instrumento educacional e preventivo, não diagnóstico clínico.</p></div><span>{score}/100</span></div><div className="form-card"><label>Unidade escolar<select value={school} onChange={e=>setSchool(e.target.value)}><option value="">Selecione</option>{data.matrix.map(x=><option key={x.Rank}>{x.Unidade}</option>)}</select></label>{qs.map((question,i)=><div className="question" key={question}><b>{i+1}. {question}</b><div className="likert">{['Nunca','Raramente','Às vezes','Frequentemente','Sempre'].map((l,j)=><button className={a[i]===j+1?'sel':''} onClick={()=>setA(v=>v.map((x,k)=>k===i?j+1:x))} key={l}>{l}</button>)}</div></div>)}<button className="primary" onClick={finish}>Finalizar avaliação</button></div></section>}

function Evidence({data,q}){const rows=data.evidencias.filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));return <section><div className="section-head"><div><small>EVIDÊNCIAS TERRITORIAIS · 3.2</small><h2>Catálogo de evidências</h2><p>Registros territoriais preservados para rastreabilidade e correlação com as unidades.</p></div><span>{rows.length} de {data.evidencias.length}</span></div><div className="table-wrap"><table><thead><tr>{['Tipo','Via/Corredor','Ponto','Natureza','Valor/resultado','Data/ano','Unidade escolar associada','Fonte oficial'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((x,i)=><tr key={i}><td>{text(x.Tipo)}</td><td>{text(x['Via/Corredor'])}</td><td>{text(x.Ponto)}</td><td>{text(x.Natureza)}</td><td>{text(x['Valor/resultado'])}</td><td>{text(x['Data/ano'])}</td><td>{text(x['Unidade escolar associada'])}</td><td>{text(x['Fonte oficial'])}</td></tr>)}</tbody></table></div></section>}

function Crashes({data}){return <section><div className="section-head"><div><small>SEGURANÇA VIÁRIA · CORREDORES</small><h2>Sinistros / Corredores</h2><p>Ranking de acidentes dos corredores presentes na base territorial 3.2.</p></div><span>{data.sinistros.length} corredores</span></div><div className="table-wrap"><table><thead><tr>{['Rank 2023','Via','Acidentes 2023','Rank 2024','Acidentes 2024','Presença nos dois anos','Score territorial máximo','Fonte'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{data.sinistros.map((x,i)=><tr key={i}><td>{text(x['Rank 2023'])}</td><td><b>{text(x.Via)}</b></td><td>{text(x['Acidentes 2023'])}</td><td>{text(x['Rank 2024'])}</td><td>{text(x['Acidentes 2024'])}</td><td>{text(x['Presença nos dois anos'])}</td><td>{text(x['Score territorial máximo'])}</td><td>{text(x.Fonte)}</td></tr>)}</tbody></table></div></section>}

function Operational({data,type,title,ops,save}){const[list,setList]=useState(ops[type]||[]),[school,setSchool]=useState(''),[t,setT]=useState('');const add=()=>{if(!school||!t)return;const r={id:Date.now(),school,text:t,status:'REGISTRADO',createdAt:new Date().toISOString()},nl=[...list,r];setList(nl);save({...ops,[type]:nl});setT('')};return <section><div className="section-head"><div><small>CAMADA OPERACIONAL</small><h2>{title}</h2><p>Registros operacionais separados da fonte territorial histórica.</p></div><span>{list.length} registros</span></div><div className="form-inline"><select value={school} onChange={e=>setSchool(e.target.value)}><option value="">Unidade escolar</option>{data.matrix.map(x=><option key={x.Rank}>{x.Unidade}</option>)}</select><input value={t} onChange={e=>setT(e.target.value)} placeholder="Descreva o registro..."/><button className="primary" onClick={add}>Registrar</button></div><div className="panel">{list.length?list.map(r=><div className="row" key={r.id}><div><b>{r.school}</b><span>{r.text}</span></div><em>{r.status}</em></div>):<div className="empty">Nenhum registro ainda.</div>}</div></section>}

function Guide({data}){const guides=data.matrix.filter(x=>String(x['Aluno Guia']).toUpperCase()==='SIM');return <section><div className="section-head"><div><small>ALUNO GUIA</small><h2>Rede de Alunos Guia</h2><p>Visão territorial dos registros existentes na matriz. O cadastro individual deverá permanecer em camada autenticada.</p></div><span>{guides.length} registros</span></div><div className="panel"><h3>Fluxo previsto</h3><p>Manifestação de interesse → HSI-DOTH-P Bullying → HSI-DOTH-P Trânsito Escolar → validação escolar → acesso ao Espaço Aluno Guia.</p><p className="note">Esta tela não expõe dados pessoais de estudantes.</p></div><div className="table-wrap"><table><thead><tr><th>Unidade</th><th>Bairro</th><th>Status na matriz</th></tr></thead><tbody>{guides.map(x=><tr key={x.Rank}><td>{x.Unidade}</td><td>{x.Bairro}</td><td>{x['Aluno Guia']}</td></tr>)}</tbody></table></div></section>}

function Formation(){const courses=['Pré-formação de Aluno Guia','NEXUS 12 — Atuação do Aluno Guia','Neuroeducação Aplicada ao Trânsito Escolar','Gestão de Riscos Escolares','Bullying e Convivência Segura','Primeiros Cuidados','Acessibilidade e Mobilidade Inclusiva'];return <section><div className="section-head"><div><small>FORMAÇÃO · ENAT</small><h2>Trilhas de formação</h2><p>Ambiente preparado para cursos livres, módulos, avaliações e certificação.</p></div><span>{courses.length} trilhas</span></div><div className="cards">{courses.map((c,i)=><div className="metric" key={c}><small>TRILHA {String(i+1).padStart(2,'0')}</small><strong>{c}</strong><span>Conteúdo · avaliação · registro</span></div>)}</div></section>}

function Reports({data,ops}){const textReport=`SIGES — RELATÓRIO EXECUTIVO\n\nUnidades: ${data.matrix.length}\nEvidências territoriais: ${data.evidencias.length}\nCorredores de sinistros: ${data.sinistros.length}\nRiscos operacionais: ${(ops.riscos||[]).length}\nReivindicações: ${(ops.reivindicacoes||[]).length}\nPlanos de ação: ${(ops.plano||[]).length}\n\nFonte: HSI-DOTH-P Escolar 3.2.\nObservação: indicadores não substituem levantamento de campo ou decisão pública.`;return <section><div className="section-head"><div><small>RELATÓRIOS</small><h2>Relatório executivo</h2></div></div><div className="panel"><pre>{textReport}</pre><button className="primary" onClick={()=>window.print()}>Imprimir / PDF</button></div></section>}

function Audit({ops}){return <section><div className="section-head"><div><small>RASTREABILIDADE</small><h2>Auditoria</h2><p>Registro local do protótipo; a arquitetura definitiva deverá persistir os eventos no backend.</p></div><span>{(ops.auditoria||[]).length} eventos</span></div><div className="panel"><p>A fonte territorial permanece somente leitura. Eventos operacionais não alteram a matriz 3.2.</p></div></section>}

function Settings({data}){return <section><div className="section-head"><div><small>ADMINISTRAÇÃO ENAT</small><h2>Configurações</h2><p>Parâmetros estruturais do ambiente SIGES.</p></div></div><div className="grid2"><div className="panel"><h3>Fonte territorial</h3><p>HSI-DOTH-P Escolar 3.2 · Joinville · somente leitura.</p><p>{data.matrix.length} unidades · {data.evidencias.length} evidências · {data.sinistros.length} corredores.</p></div><div className="panel"><h3>Interoperabilidade</h3><p>Preparado para integração futura por APIs autorizadas, sem compartilhamento direto de banco.</p></div><div className="panel"><h3>IA</h3><p>IA deverá explicar, correlacionar e recomendar; não aprovar, excluir evidências, alterar HSI ou substituir decisão humana.</p></div><div className="panel"><h3>Privacidade</h3><p>Indicadores agregados e minimização de dados pessoais.</p></div></div></section>}

createRoot(document.getElementById('root')).render(<App/>);
