import React,{useEffect,useState}from'react';
import{Database,RefreshCw,ExternalLink,CheckCircle2,AlertTriangle,Clock3,MapPinned,Route}from'lucide-react';
import'./public-sources.css';
const fmt=v=>v==null?'—':typeof v==='number'?v.toLocaleString('pt-BR'):v;
function SourceCard({name,desc,active,onClick}){return <button className={`source-card ${active?'active':'planned'}`} onClick={onClick}><div className="source-icon"><Database size={20}/></div><div><b>{name}</b><span>{desc}</span></div><em>{active?<><CheckCircle2 size={14}/> CONECTADO</>:'CONECTOR ATIVO'}</em></button>}
export default function PublicSources(){const[data,setData]=useState(null),[tab,setTab]=useState('cbvj'),[loading,setLoading]=useState(true),[error,setError]=useState('');async function load(kind=tab){setLoading(true);setError('');try{const r=await fetch(`/api/public-sources/${kind}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha na consulta');setData(j)}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load('cbvj')},[]);function select(k){setTab(k);load(k)}return <section>
<div className="section-head"><div><small>CENTRAL DE FONTES · DADOS PÚBLICOS</small><h2>Fontes e Dados Externos</h2><p>Conectores somente leitura para enriquecer a inteligência territorial do SIGES sem alterar as fontes originais.</p></div><button className="primary" onClick={()=>load(tab)} disabled={loading}><RefreshCw size={15}/> {loading?'Consultando':'Atualizar fonte'}</button></div>
{error&&<div className="source-alert"><AlertTriangle size={18}/><div><b>Fonte temporariamente indisponível</b><span>{error}</span></div></div>}
<div className="source-grid"><SourceCard name="CBVJ" desc="Ocorrências e ranking de corredores" active={tab==='cbvj'} onClick={()=>select('cbvj')}/><SourceCard name="DETRANS" desc="Estudos técnicos e evidências viárias" active={tab==='detrans'} onClick={()=>select('detrans')}/><SourceCard name="SIMGEO" desc="Camadas geográficas e território" active={tab==='simgeo'} onClick={()=>select('simgeo')}/></div>
{data&&<><div className="source-meta"><div><small>ÚLTIMO ANO</small><strong>{fmt(data.latestCompleteYear)}</strong></div><div><small>ÚLTIMA PUBLICAÇÃO</small><strong>{data.latestPublicationDate?new Date(data.latestPublicationDate+'T12:00:00').toLocaleDateString('pt-BR'):'Não aplicável'}</strong></div><div><small>TOTAL DE OCORRÊNCIAS</small><strong>{fmt(data.summary?.totalOccurrences2025??data.summary?.totalOccurrences)}</strong></div><div><small>ÚLTIMA LEITURA SIGES</small><strong>{new Date(data.retrievedAt).toLocaleString('pt-BR')}</strong></div></div>
{tab==='cbvj'&&<><div className="panel"><div className="section-head"><div><small>CBVJ · RANKING DE VIAS</small><h3>Corredores com maior número de acidentes</h3></div><a href={data.urls?.2025} target="_blank" rel="noreferrer">Abrir publicação <ExternalLink size={14}/></a></div><div className="table-wrap"><table><thead><tr><th>Rank 2025</th><th>Corredor</th><th>2024 · publicação 2025</th><th>2025</th><th>Variação</th></tr></thead><tbody>{(data.corridors||[]).map(x=><tr key={x.road}><td>{x.rank2025}</td><td><b>{x.road}</b></td><td>{fmt(x.value2024)}</td><td>{fmt(x.value2025)}</td><td>{x.variation2024to2025==null?'—':`${x.variation2024to2025>0?'+':''}${x.variation2024to2025.toFixed(2)}%`}</td></tr>)}</tbody></table></div></div></>}
{tab==='detrans'&&<><div className="panel"><div className="section-head"><div><small>DETRANS · EVIDÊNCIA TÉCNICA</small><h3>Corredores com estudos publicados</h3></div><a href={data.urls?.publication} target="_blank" rel="noreferrer">Abrir publicação original <ExternalLink size={14}/></a></div><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Corredor</th><th>Estudos</th></tr></thead><tbody>{(data.corridors||[]).slice(0,25).map(x=><tr key={x.road}><td>{x.rank}</td><td><b>{x.road}</b></td><td>{x.count}</td></tr>)}</tbody></table></div></div><div className="source-note"><Route size={16}/><span><b>Critério:</b> ranking por quantidade de estudos DETRANS identificados na publicação oficial. Isso mede presença de evidência técnica, não número de acidentes.</span></div></>}
{tab==='simgeo'&&<><div className="panel"><div className="section-head"><div><small>SIMGEO · INTELIGÊNCIA GEOGRÁFICA</small><h3>Inventário territorial disponível</h3></div><a href={data.urls?.portal} target="_blank" rel="noreferrer">Abrir SIMGeo <ExternalLink size={14}/></a></div><div className="cards"><div className="metric"><small>Unidades escolares</small><strong>{fmt(data.summary?.schoolUnits)}</strong><span>camada pública</span></div><div className="metric"><small>Camadas planejamento</small><strong>{fmt(data.summary?.planningLayers)}</strong><span>inventário consultado</span></div><div className="metric"><small>Ocorrências</small><strong>—</strong><span>não fornecidas por esta consulta</span></div></div><div className="layer-list">{(data.layers||[]).slice(0,20).map(x=><div key={x.id}><MapPinned size={15}/><span>{x.name}</span><em>{x.type}</em></div>)}</div></div><div className="source-note"><Clock3 size={16}/><span><b>Rastreabilidade:</b> o SIGES consulta somente metadados e contagens agregadas. Nenhuma camada do SIMGeo é alterada pelo sistema.</span></div></>}
<div className="source-note"><Clock3 size={16}/><span><b>Rastreabilidade:</b> fonte, URL original, data da leitura e metodologia permanecem identificáveis. Quando uma fonte não oferece uma série anual comparável, o SIGES exibe “—” em vez de inventar variação ou ocorrência.</span></div></>}
</section>}
