"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Building2,ClipboardCheck,ExternalLink,MapPin,ShieldAlert,Target,Users} from "lucide-react";
import {supabase} from "@/lib/supabase";

type Unit={id:string;name:string;unit_type:string;neighborhood:string;address:string;rank:number;hsi:number;ipe:number;priority:string;confidence_score:number;technical_evidence_score:number;public_evidence_score:number;data_status:string;speed_kmh:number|null;vdm:number|null;crashes_3y:number|null;crossings:number|null;sidewalk:string|null;signage:string|null;lighting:string|null;pickup_dropoff:string|null;cyclists:string|null;recommended_action:string|null;observations:string|null};
type Evidence={id:string;evidence_type:string;status:string;description:string|null;source_name:string|null;source_url:string|null;source_date:string|null;confidence:string|null};
const pc=(p:string)=>p?.startsWith("P1")?"p1":p?.startsWith("P2")?"p2":p?.startsWith("P3")?"p3":"p4";
const val=(v:any)=>v===null||v===undefined||v===""?"Não informado":String(v);
export default function Escola(){
 const id=typeof window!=="undefined"?window.location.pathname.split("/").filter(Boolean).pop():"";
 const [u,setU]=useState<Unit|null>(null);const [ev,setEv]=useState<Evidence[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!id)return;(async()=>{const a=await supabase().from("units").select("*").eq("id",id).single();setU(a.data);const b=await supabase().from("evidence").select("*").eq("unit_id",id).order("created_at",{ascending:false});setEv(b.data||[]);setLoading(false)})()},[id]);
 if(loading)return <main className="min-h-screen p-4 md:p-8 max-w-[1300px] mx-auto"><div className="card p-8 animate-pulse h-64"/></main>;
 if(!u)return <main className="min-h-screen p-4 md:p-8 max-w-[1300px] mx-auto"><Link href="/escolas" className="muted"><ArrowLeft size={15} className="inline mr-1"/> Voltar</Link><div className="card p-8 mt-5">Unidade não encontrada.</div></main>;
 return <main className="min-h-screen p-4 md:p-8 max-w-[1300px] mx-auto"><div className="mb-5"><Link href="/escolas" className="muted text-sm hover:text-cyan-300"><ArrowLeft size={15} className="inline mr-1"/> Escolas</Link></div>
 <header className="card p-5 md:p-7 mb-5"><div className="flex flex-col md:flex-row md:justify-between gap-4"><div><div className="text-cyan-300 text-xs font-bold tracking-widest">DOSSIÊ INTEGRADO DA UNIDADE</div><h1 className="text-2xl md:text-4xl font-black mt-2 leading-tight">{u.name}</h1><p className="muted mt-2 flex items-start gap-1"><MapPin size={15} className="mt-0.5 shrink-0"/>{u.address} · {u.neighborhood}</p></div><span className={`pill ${pc(u.priority)} h-fit text-sm`}>{u.priority}</span></div></header>
 <section className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">{[['HSI',u.hsi],['IPE',u.ipe],['Confiabilidade',`${val(u.confidence_score)}%`],['Evidência técnica',val(u.technical_evidence_score)]].map(([l,v]:any)=><div className="card p-4" key={l}><div className="muted text-xs">{l}</div><div className="text-2xl font-black mt-2">{v}</div></div>)}</section>
 <section className="grid lg:grid-cols-3 gap-4 mb-5"><div className="card p-5 lg:col-span-2"><div className="flex items-center gap-2 font-bold"><ShieldAlert size={18}/> Situação de risco</div><p className="muted text-sm mt-3">{val(u.recommended_action)}</p><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5">{[['Velocidade',u.speed_kmh?`${u.speed_kmh} km/h`:null],['VDM',u.vdm],['Sinistros · 3 anos',u.crashes_3y],['Travessias',u.crossings]].map(([l,v]:any)=><div className="bg-[#091624] rounded-xl p-3" key={l}><div className="muted text-xs">{l}</div><strong className="block mt-1">{val(v)}</strong></div>)}</div></div><div className="card p-5"><div className="flex items-center gap-2 font-bold"><Target size={18} className="text-cyan-300"/> Prioridade</div><div className={`pill ${pc(u.priority)} mt-4`}>{u.priority}</div><p className="muted text-sm mt-4">Classificação de triagem do SIGES. Dado ausente não significa risco ausente.</p></div></section>
 <section className="grid md:grid-cols-2 gap-4 mb-5"><div className="card p-5"><h2 className="font-bold">Infraestrutura e entorno</h2><div className="grid grid-cols-2 gap-3 mt-4">{[['Calçada',u.sidewalk],['Sinalização',u.signage],['Iluminação',u.lighting],['Embarque/desembarque',u.pickup_dropoff],['Ciclistas',u.cyclists]].map(([l,v]:any)=><div key={l} className="bg-[#091624] rounded-xl p-3"><div className="muted text-xs">{l}</div><div className="text-sm mt-1">{val(v)}</div></div>)}</div></div><div className="card p-5"><h2 className="font-bold">Observações</h2><p className="muted text-sm mt-4 leading-relaxed">{val(u.observations)}</p><div className="mt-5 text-xs muted">Status dos dados: <strong>{val(u.data_status)}</strong></div></div></section>
 <section className="card p-5 mb-5"><div className="flex items-center justify-between"><div><h2 className="font-bold flex items-center gap-2"><ClipboardCheck size={18} className="text-cyan-300"/> Evidências</h2><p className="muted text-xs mt-1">Fontes que sustentam a leitura desta unidade.</p></div><span className="pill p3">{ev.length} registros</span></div><div className="mt-4 space-y-3">{ev.length?ev.map(e=><div className="bg-[#091624] rounded-xl p-4" key={e.id}><div className="flex justify-between gap-3"><div><strong>{e.evidence_type}</strong><div className="muted text-xs mt-1">{e.source_name||"Fonte não informada"} · {e.status} · confiabilidade {e.confidence||"não informada"}</div></div>{e.source_url&&<a href={e.source_url} target="_blank" rel="noreferrer" className="text-cyan-300"><ExternalLink size={16}/></a>}</div>{e.description&&<p className="muted text-sm mt-3">{e.description}</p>}</div>):<p className="muted text-sm">Nenhuma evidência específica registrada ainda.</p>}</div></section>
 <section className="grid grid-cols-1 sm:grid-cols-3 gap-3"><Link href="/aluno-guia" className="card p-4 hover:bg-[#102337]"><Users size={18} className="text-cyan-300"/><strong className="block mt-2">Aluno Guia</strong><span className="muted text-xs">Abrir módulo de análise individual</span><ArrowRight size={15} className="mt-3"/></Link><Link href="/mapa" className="card p-4 hover:bg-[#102337]"><MapPin size={18} className="text-cyan-300"/><strong className="block mt-2">Ver no mapa</strong><span className="muted text-xs">Localização e contexto territorial</span><ArrowRight size={15} className="mt-3"/></Link><Link href="/intervencoes" className="card p-4 hover:bg-[#102337]"><Building2 size={18} className="text-cyan-300"/><strong className="block mt-2">Intervenções</strong><span className="muted text-xs">Acompanhar ações desta unidade</span><ArrowRight size={15} className="mt-3"/></Link></section>
 </main>
}
