"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BookOpen,Download,FileText,MapPin,ShieldAlert,Users} from "lucide-react";
import {supabase} from "@/lib/supabase";

type Unit={id:string;name:string;unit_type:string;neighborhood:string|null;address:string|null;rank:number;hsi:number|null;ipe:number|null;ipe_territorial:number|null;priority:string|null;territorial_priority:string|null;territorial_confidence:string|null;territorial_justification:string|null;student_guide:string|null;detrans_in_corridor:string|null;detrans_studies_count:number|null;detrans_proximity:string|null;detrans_point:number|null;accidents_corridor_2023:number|null;accidents_corridor_2024:number|null;accident_rank_2024:number|null;accident_evidence_score:number|null;detrans_evidence_score:number|null;territorial_data_available:string|null;recommended_action:string|null};
type Context={metric_key:string;metric_label:string;value_numeric:number|null;value_text:string|null;unit:string|null;category:string;notes:string|null};

const pcode=(p:string|null)=>p?.startsWith("P1")?"P1":p?.startsWith("P2")?"P2":p?.startsWith("P3")?"P3":"P4";
const pill=(p:string)=>p==="P1"?"bg-red-950/70 text-red-200 border-red-800":p==="P2"?"bg-orange-950/70 text-orange-200 border-orange-800":"bg-slate-800 text-slate-200 border-slate-700";
const fmt=(v:any)=>v===null||v===undefined||v===""?"Não informado":String(v);

function buildRecommendation(u:Unit){
 const p=pcode(u.territorial_priority);
 if(p==="P1") return "Implantar o Aluno Guia com prioridade imediata, precedida de validação de campo, definição dos horários críticos e treinamento/coordenação com a Escola Pública de Trânsito e o DETRANS.";
 return "Programar o Aluno Guia como intervenção prioritária, realizando validação de campo do entorno, definição dos horários de maior conflito e treinamento/coordenação com a Escola Pública de Trânsito e o DETRANS.";
}
function buildJustification(u:Unit){
 const p=pcode(u.territorial_priority);
 const parts:string[]=[];
 parts.push(`A unidade está classificada como ${p} na prioridade territorial HSI-DOTH-P 3.2, com IPE Territorial ${fmt(u.ipe_territorial??u.ipe)} e confiabilidade territorial ${fmt(u.territorial_confidence)}.`);
 if(u.detrans_in_corridor==="SIM") parts.push(`Há correspondência com corredor que possui evidência do DETRANS${u.detrans_studies_count?` e ${u.detrans_studies_count} estudo(s) associado(s)`:""}.`);
 else if(u.detrans_proximity&&u.detrans_proximity!=="Não identificado") parts.push(`Foi identificada proximidade/correspondência territorial com referência do DETRANS (${u.detrans_proximity}).`);
 if(u.accident_rank_2024!==null&&u.accident_rank_2024!==undefined) parts.push(`A via/corredor possui posição registrada no ranking de acidentes de 2024 (${u.accident_rank_2024}).`);
 else if(u.accidents_corridor_2023!==null||u.accidents_corridor_2024!==null) parts.push(`Existem registros municipais de acidentes com vítimas associados ao corredor, com ${fmt(u.accidents_corridor_2023)} em 2023 e ${fmt(u.accidents_corridor_2024)} em 2024.`);
 if(u.territorial_justification) parts.push(u.territorial_justification);
 parts.push("A recomendação é de proteção/organização da travessia escolar; não substitui estudo de engenharia, fiscalização ou validação presencial.");
 return parts.join(" ");
}

export default function RelatorioAlunoGuia(){
 const [units,setUnits]=useState<Unit[]>([]);const [ctx,setCtx]=useState<Context[]>([]);const [loading,setLoading]=useState(true);const [q,setQ]=useState("");
 useEffect(()=>{(async()=>{setLoading(true);const [u,c]=await Promise.all([supabase().from("units").select("*").in("territorial_priority",["P1","P2"]).order("territorial_priority",{ascending:true}).order("ipe_territorial",{ascending:false}),supabase().from("city_data_context").select("metric_key,metric_label,value_numeric,value_text,unit,category,notes").order("category")]);setUnits((u.data as Unit[])||[]);setCtx((c.data as Context[])||[]);setLoading(false)})()},[]);
 const filtered=useMemo(()=>units.filter(u=>`${u.name} ${u.neighborhood||""} ${u.address||""}`.toLowerCase().includes(q.toLowerCase())),[units,q]);
 const p1=filtered.filter(u=>pcode(u.territorial_priority)==="P1").length;const p2=filtered.filter(u=>pcode(u.territorial_priority)==="P2").length;
 const get=(k:string)=>ctx.find(c=>c.metric_key===k);
 const print=()=>window.print();
 return <main className="min-h-screen p-4 md:p-8 max-w-[1600px] mx-auto print:bg-white print:text-black">
  <header className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4 mb-6 print:mb-4"><div><Link href="/aluno-guia" className="muted text-sm flex items-center gap-2 mb-3 print:hidden"><ArrowLeft size={15}/> Módulo Aluno Guia</Link><div className="text-cyan-300 text-xs font-bold tracking-widest">SIGES • RELATÓRIO TERRITORIAL</div><h1 className="text-3xl md:text-4xl font-black mt-1">Escolas prioritárias para Aluno Guia</h1><p className="muted mt-2 max-w-4xl">Relatório analítico baseado na prioridade territorial HSI-DOTH-P 3.2 e nas evidências municipais disponíveis. Recomendação e justificativa são geradas a partir dos campos mensurados do SIGES.</p></div><button onClick={print} className="card px-4 py-3 flex items-center gap-2 print:hidden"><Download size={17}/> Imprimir / PDF</button></header>
  <section className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5"><div className="card p-4"><div className="muted text-xs">Escolas prioritárias</div><div className="text-3xl font-black mt-1">{units.length}</div><div className="muted text-xs">P1 + P2</div></div><div className="card p-4"><div className="muted text-xs">P1 · crítica</div><div className="text-3xl font-black mt-1">{p1}</div></div><div className="card p-4"><div className="muted text-xs">P2 · muito alta</div><div className="text-3xl font-black mt-1">{p2}</div></div><div className="card p-4"><div className="muted text-xs">Base de trabalho</div><div className="text-3xl font-black mt-1">162</div><div className="muted text-xs">unidades cadastradas</div></div></section>
  <section className="card p-5 mb-5"><div className="flex items-center gap-2 font-bold"><BookOpen size={18} className="text-cyan-300"/> Contexto municipal — Joinville Cidade em Dados 2025</div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-4">{[["vias_pavimentadas_pct","Vias pavimentadas"],["rede_cicloviaria_total_km","Rede cicloviária"],["onibus_usuarios_dia_medio","Usuários de ônibus/dia"],["frota_total","Veículos em circulação"]].map(([k,l])=>{const c=get(k);return <div className="bg-[#091624] rounded-xl p-3" key={k}><div className="muted text-xs">{l}</div><strong className="block text-lg mt-1">{c?`${c.value_numeric}${c.unit?` ${c.unit}`:""}`:"Não informado"}</strong><div className="muted text-[11px] mt-1">Fonte: Cidade em Dados 2025</div></div>})}</div><p className="muted text-xs mt-4">O contexto municipal é complementar: a indicação de Aluno Guia é feita pela evidência territorial da unidade, e não por um indicador municipal isolado.</p></section>
  <section className="card p-4 mb-5 print:hidden"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar escola, bairro ou endereço..." className="w-full bg-[#07111f] rounded-xl px-4 py-3 outline-none"/></section>
  <section className="space-y-4">{loading?<div className="card p-8">Carregando relatório...</div>:filtered.map(u=>{const p=pcode(u.territorial_priority);return <article className="card p-5 md:p-6 print:break-inside-avoid" key={u.id}><div className="flex flex-col xl:flex-row xl:items-start xl:justify-between gap-4"><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><span className={`px-3 py-1 rounded-full border text-xs font-bold ${pill(p)}`}>{p}</span><span className="muted text-xs">#{u.rank} · {u.unit_type}</span></div><h2 className="text-xl md:text-2xl font-black mt-3">{u.name}</h2><p className="muted text-sm mt-1 flex items-start gap-1"><MapPin size={15} className="mt-0.5 shrink-0"/>{fmt(u.address)} · {fmt(u.neighborhood)}</p></div><Link href={`/escolas/${u.id}`} className="text-cyan-300 text-sm font-semibold print:hidden">Abrir dossiê →</Link></div><div className="grid md:grid-cols-3 gap-3 mt-5"><div className="bg-[#091624] rounded-xl p-4"><div className="muted text-xs">HSI / IPE Territorial</div><strong className="text-lg">{fmt(u.hsi)} / {fmt(u.ipe_territorial??u.ipe)}</strong></div><div className="bg-[#091624] rounded-xl p-4"><div className="muted text-xs">DETRANS</div><strong className="text-sm">{fmt(u.detrans_in_corridor)}</strong><div className="muted text-xs mt-1">{fmt(u.detrans_proximity)} · estudos: {fmt(u.detrans_studies_count)}</div></div><div className="bg-[#091624] rounded-xl p-4"><div className="muted text-xs">Acidentes / evidência</div><strong className="text-sm">2023: {fmt(u.accidents_corridor_2023)} · 2024: {fmt(u.accidents_corridor_2024)}</strong><div className="muted text-xs mt-1">Ranking 2024: {fmt(u.accident_rank_2024)}</div></div></div><div className="grid lg:grid-cols-2 gap-4 mt-5"><div className="rounded-xl border border-cyan-900/70 bg-cyan-950/20 p-4"><div className="flex items-center gap-2 font-bold"><Users size={17} className="text-cyan-300"/> Recomendação</div><p className="text-sm leading-6 mt-3">{buildRecommendation(u)}</p></div><div className="rounded-xl border border-[#26394c] bg-[#07111f] p-4"><div className="flex items-center gap-2 font-bold"><ShieldAlert size={17} className="text-cyan-300"/> Justificativa baseada nos dados</div><p className="text-sm leading-6 mt-3">{buildJustification(u)}</p></div></div></article>})}</section>
  {!loading&&!filtered.length&&<div className="card p-8 text-center muted">Nenhuma escola P1/P2 corresponde à pesquisa.</div>}
  <footer className="muted text-xs mt-6 print:mt-4">Fonte contextual: Prefeitura de Joinville, Joinville Cidade em Dados 2025. A classificação e as recomendações do SIGES são analíticas; a implantação operacional do Aluno Guia requer validação de campo e coordenação com os órgãos competentes.</footer>
 </main>;
}
