"use client";
import{useEffect,useMemo,useState}from"react";
import Link from"next/link";
import{ArrowLeft,BarChart3,Plus,Save,TrendingUp}from"lucide-react";
import{supabase}from"@/lib/supabase";

type Project={id:string;name:string;status:string;school_count:number;phase_count:number;baseline:any;targets:any};
type Result={id:string;project_id:string;unit_id:string|null;measurement_stage:string;measured_at:string;indicator:string;value_numeric:number|null;value_text:string|null;source:string|null;notes:string|null};
export default function Resultados(){const[projects,setProjects]=useState<Project[]>([]),[results,setResults]=useState<Result[]>([]),[project,setProject]=useState(""),[stage,setStage]=useState("T1_INTERVENCAO"),[indicator,setIndicator]=useState("HSI"),[value,setValue]=useState(""),[source,setSource]=useState("Validação SIGES"),[notes,setNotes]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const[p,r]=await Promise.all([supabase().from("strategy_projects").select("*").order("created_at",{ascending:false}),supabase().from("strategy_results").select("*").order("measured_at",{ascending:false})]);setProjects((p.data as Project[])||[]);setResults((r.data as Result[])||[])};useEffect(()=>{load()},[]);
 const selected=projects.find(p=>p.id===project);const stages=useMemo(()=>selected?results.filter(r=>r.project_id===selected.id):results,[selected,results]);
 const save=async()=>{if(!project||!indicator){setMessage("Selecione um projeto e um indicador.");return}const{error}=await supabase().from("strategy_results").insert({project_id:project,measurement_stage:stage,indicator,value_numeric:value?Number(value):null,source,notes});setMessage(error?`Erro: ${error.message}`:"Medição registrada.");if(!error){setValue("");setNotes("");load()}};
 return <main className="min-h-screen p-4 md:p-8 max-w-[1400px] mx-auto"><Link href="/estrategia" className="muted text-sm flex items-center gap-2 mb-4"><ArrowLeft size={15}/> Centro Estratégico</Link><div className="text-cyan-300 text-xs font-bold tracking-[.22em]">SIGES 3.5 • RESULTADOS</div><h1 className="text-3xl md:text-5xl font-black mt-1">Baseline, metas e resultados</h1><p className="muted mt-2 max-w-4xl">Registre medições reais em T0, T1 e T2. O painel não transforma ausência de dados em zero e não calcula melhoria sem medições comparáveis.</p>
 <section className="grid lg:grid-cols-[.9fr_1.1fr] gap-5 mt-6"><div className="card p-5"><div className="flex items-center gap-2 font-bold mb-4"><BarChart3 size={18} className="text-cyan-300"/> Registrar medição</div><label className="muted text-xs">PROJETO</label><select value={project} onChange={e=>setProject(e.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"><option value="">Selecione...</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><label className="muted text-xs">ESTÁGIO</label><select value={stage} onChange={e=>setStage(e.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"><option>T0_BASELINE</option><option>T1_INTERVENCAO</option><option>T2_POS_INTERVENCAO</option></select><label className="muted text-xs">INDICADOR</label><select value={indicator} onChange={e=>setIndicator(e.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"><option>HSI</option><option>IPE_TERRITORIAL</option><option>PERCEPCAO_RISCO</option><option>COMPORTAMENTO_RISCO</option><option>ALUNO_GUIA</option><option>OUTRO</option></select><label className="muted text-xs">VALOR NUMÉRICO</label><input value={value} onChange={e=>setValue(e.target.value)} type="number" step="0.01" className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"/><label className="muted text-xs">FONTE</label><input value={source} onChange={e=>setSource(e.target.value)} className="w-full mt-1 mb-3 bg-[#07111f] rounded-xl p-3"/><label className="muted text-xs">NOTAS</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} className="w-full mt-1 bg-[#07111f] rounded-xl p-3 min-h-20"/><button onClick={save} className="mt-4 px-5 py-3 rounded-xl bg-cyan-800 hover:bg-cyan-700 font-bold flex gap-2 items-center"><Save size={17}/> Registrar</button>{message&&<p className="muted text-sm mt-3">{message}</p>}</div>
 <div className="card p-5"><div className="flex items-center gap-2 font-bold"><TrendingUp size={18} className="text-cyan-300"/> Leitura do projeto</div>{selected?<><div className="grid grid-cols-3 gap-3 mt-4"><div className="bg-[#07111f] rounded-xl p-3"><div className="muted text-xs">Escolas</div><b className="text-2xl">{selected.school_count}</b></div><div className="bg-[#07111f] rounded-xl p-3"><div className="muted text-xs">Fases</div><b className="text-2xl">{selected.phase_count}</b></div><div className="bg-[#07111f] rounded-xl p-3"><div className="muted text-xs">Medições</div><b className="text-2xl">{stages.length}</b></div></div><div className="mt-5 space-y-2">{stages.length?stages.map(r=><div key={r.id} className="rounded-xl bg-[#07111f] p-3"><div className="flex justify-between"><b>{r.indicator}</b><span className="text-xs text-cyan-300">{r.measurement_stage}</span></div><div className="muted text-sm mt-1">Valor: {r.value_numeric??r.value_text??"Não informado"} · {r.source||"Fonte não informada"}</div></div>):<div className="muted">Ainda não há medições para este projeto.</div>}</div></>:<div className="muted mt-5">Selecione um projeto para acompanhar os resultados.</div>}</div></section>
 <section className="card p-5 mt-5"><h2 className="font-bold">Regra de interpretação</h2><p className="muted text-sm mt-2">T0 estabelece a linha de base. T1 documenta a intervenção. T2 permite avaliar mudança quando houver dados comparáveis. O SIGES registra o fato observado e sua fonte; a interpretação causal depende do desenho de avaliação adotado.</p></section></main>}