-- Idempotent seed of official/public sources. Does not download or import source datasets.
insert into public.data_source_catalog
  (slug, organization, name, homepage_url, catalog_url, access_method, expected_frequency, license_notes, metadata)
values
  ('renaest','Ministério dos Transportes / SENATRAN','RENAEST — Sinistros de trânsito','https://www.gov.br/transportes/pt-br','https://dados.transportes.gov.br/api/3/action/package_show?id=renaest','catalog_api','Mensal, conforme catálogo','Confirmar termos do conjunto e atribuição antes da publicação.','{"domain":"traffic","priority":"P0","formats":["ZIP","CSV"],"notes":"O coletor atual limita arquivos ZIP a 50 MiB e não persiste os resultados."}'::jsonb),
  ('inep_escolas','INEP','Catálogo de Escolas','https://www.gov.br/inep/pt-br','https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/inep-data/catalogo-de-escolas','download','Anual, conforme Censo Escolar','Validar licença e versão de cada arquivo.','{"domain":"education","priority":"P0","key":"codigo_inep"}'::jsonb),
  ('ibge_municipios','IBGE','Códigos oficiais dos municípios','https://www.ibge.gov.br/','https://www.ibge.gov.br/explica/codigos-dos-municipios.php','download','Conforme atualização do IBGE','Usar código oficial do município como chave territorial.','{"domain":"territory","priority":"P0","key":"codigo_ibge"}'::jsonb),
  ('prf_sinistros','Polícia Rodoviária Federal','Dados Abertos PRF — Sinistros','https://www.gov.br/prf/pt-br','https://www.gov.br/prf/pt-br/acesso-a-informacao/dados-abertos/dados-abertos-da-prf','download','Conforme publicação oficial','Verificar condições de uso e conciliação com RENAEST/DNIT.','{"domain":"traffic","priority":"P1","deduplication":"Não somar automaticamente com RENAEST/DNIT."}'::jsonb),
  ('dnit_sinistros','DNIT','Sinistros de trânsito em rodovias federais','https://www.gov.br/dnit/pt-br','https://www.gov.br/dnit/pt-br/assuntos/infraestrutura-rodoviaria/sinistros-de-transito/sinistros-de-transito','download','Mensal, conforme publicação do órgão','Identificar se o recurso é derivado da PRF e evitar dupla contagem.','{"domain":"traffic_infrastructure","priority":"P1","deduplication":"Fonte possivelmente derivada de dados PRF."}'::jsonb),
  ('senatran_frota','SENATRAN','Frota de veículos','https://www.gov.br/transportes/pt-br/assuntos/transito/senatran','https://www.gov.br/transportes/pt-br/assuntos/transito/conteudo-Senatran/frota-de-veiculos-2026','download','Mensal, conforme publicação','Registrar mês de referência e esquema de cada planilha.','{"domain":"vehicle_fleet","priority":"P1"}'::jsonb),
  ('sus_hospitais_leitos','Ministério da Saúde','Hospitais e leitos — Dados Abertos SUS','https://dadosabertos.saude.gov.br/','https://dadosabertos.saude.gov.br/api/3/action/package_show?id=hospitais-e-leitos','catalog_api','Conforme conjunto','Preferir dados agregados; não importar identificadores pessoais desnecessários.','{"domain":"health","priority":"P1","existing_backend_reference":true}'::jsonb),
  ('simgeo_joinville','Prefeitura de Joinville','SIMGeo — camadas geográficas municipais','https://www.joinville.sc.gov.br/','https://geo.joinville.sc.gov.br/server/rest/services/simgeo','arcgis_rest','Conforme camada','Validar licença, limites de consulta e atualização de cada camada.','{"domain":"geospatial","priority":"P1","municipality":"Joinville/SC","existing_backend_reference":true}'::jsonb),
  ('inmet_historico','INMET','Dados meteorológicos históricos','https://portal.inmet.gov.br/','https://portal.inmet.gov.br/dadoshistoricos','download','Conforme publicação','Relacionar observação à estação e horário; documentar método espacial.','{"domain":"weather","priority":"P2"}'::jsonb),
  ('pemob_2025','Ministério das Cidades','Pesquisa Nacional de Mobilidade Urbana — PEMOB 2025','https://www.gov.br/cidades/pt-br','https://www.gov.br/cidades/pt-br/assuntos/mobilidade-urbana/pesquisa-nacional-de-mobilidade-urbana-pemob-2025','download','Por edição da pesquisa','Validar cobertura territorial e universo respondente.','{"domain":"mobility","priority":"P2"}'::jsonb),
  ('dados_sc','Governo do Estado de Santa Catarina','Portal de Dados Abertos SC','https://dados.sc.gov.br/','https://dados.sc.gov.br/','manual_review','Varia por conjunto','Registrar licença e política de uso de cada dataset.','{"domain":"state_open_data","priority":"P2","requires_dataset_discovery":true}'::jsonb),
  ('cbvj_joinville','Corpo de Bombeiros Voluntários de Joinville','Relatórios de ocorrências CBVJ','https://www.cbvj.org.br/','https://www.cbvj.org.br/blog/bombeiros-voluntarios-de-joinville-atenderam-14-574-ocorrencias-em-2025/','manual_review','Anual, conforme publicação','Manter metodologia e ano de referência explícitos; não confundir ocorrências atendidas com sinistros viários.','{"domain":"emergency_response","priority":"P2","existing_backend_reference":true}'::jsonb),
  ('detrans_joinville','DETRANS Joinville','Estudos técnicos de fiscalização eletrônica','https://www.joinville.sc.gov.br/','https://www.joinville.sc.gov.br/publicacoes/estudos-tecnicos-equipamentos-de-fiscalizacao-eletronica-radares-e-lombadas/','manual_review','Conforme publicação','Validar data, localização e método antes de cruzar com sinistros.','{"domain":"road_safety_measures","priority":"P1","existing_backend_reference":true}'::jsonb)
on conflict (slug) do update set
  organization = excluded.organization,
  name = excluded.name,
  homepage_url = excluded.homepage_url,
  catalog_url = excluded.catalog_url,
  access_method = excluded.access_method,
  expected_frequency = excluded.expected_frequency,
  license_notes = excluded.license_notes,
  metadata = excluded.metadata,
  updated_at = now();
